### ISSUE TITLE
Updating docker-ce to 18.09.03 on raspbian stretch displays "Cannot connect to the Docker daemon at unix:///var/run/docker.sock"

### ISSUE THREAD

**Issue by JackoPR1** [btcpayserver/btcpayserver-docker#110]
service docker status
```
● docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sun 2019-03-10 15:05:31 AST; 5min ago
     Docs: https://docs.docker.com
  Process: 2917 ExecStart=/usr/bin/dockerd -H unix:// (code=exited, status=2)
 Main PID: 2917 (code=exited, status=2)
      CPU: 961ms

Mar 10 15:05:28 raspberrypi dockerd[2917]:         /go/src/github.com/docker/docker/cmd/dockerd/docker.go:70 +0x90
Mar 10 15:05:28 raspberrypi systemd[1]: Failed to start Docker Application Container Engine.
Mar 10 15:05:28 raspberrypi systemd[1]: docker.service: Unit entered failed state.
Mar 10 15:05:28 raspberrypi systemd[1]: docker.service: Failed with result 'exit-code'.
Mar 10 15:05:31 raspberrypi systemd[1]: docker.service: Service hold-off time over, scheduling restart.
Mar 10 15:05:31 raspberrypi systemd[1]: Stopped Docker Application Container Engine.
Mar 10 15:05:31 raspberrypi systemd[1]: docker.service: Start request repeated too quickly.
Mar 10 15:05:31 raspberrypi systemd[1]: Failed to start Docker Application Container Engine.
Mar 10 15:05:31 raspberrypi systemd[1]: docker.service: Unit entered failed state.
Mar 10 15:05:31 raspberrypi systemd[1]: docker.service: Failed with result 'exit-code'.
```

journalctl -xe
```
Mar 10 15:17:17 raspberrypi dockerd[3300]:         /go/src/github.com/docker/docker/daemon/daemon.go:419 +0xa80
Mar 10 15:17:17 raspberrypi dockerd[3300]: github.com/docker/docker/daemon.NewDaemon(0x2473748, 0x1398b800, 0x13a58500, 0x134abec0, 0x0, 0x0, 0x0)
Mar 10 15:17:17 raspberrypi dockerd[3300]:         /go/src/github.com/docker/docker/daemon/daemon.go:987 +0x249c
Mar 10 15:17:17 raspberrypi dockerd[3300]: main.(*DaemonCli).start(0x1398a700, 0x134ab3e0, 0x0, 0x0)
Mar 10 15:17:17 raspberrypi systemd[1]: docker.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Mar 10 15:17:17 raspberrypi dockerd[3300]:         /go/src/github.com/docker/docker/cmd/dockerd/daemon.go:180 +0x614
Mar 10 15:17:17 raspberrypi dockerd[3300]: main.runDaemon(0x134ab3e0, 0x134e6780, 0x0)
Mar 10 15:17:17 raspberrypi dockerd[3300]:         /go/src/github.com/docker/docker/cmd/dockerd/docker_unix.go:7 +0x34
Mar 10 15:17:17 raspberrypi dockerd[3300]: main.newDaemonCommand.func1(0x13982140, 0x1341cd50, 0x0, 0x2, 0x0, 0x0)
Mar 10 15:17:17 raspberrypi dockerd[3300]:         /go/src/github.com/docker/docker/cmd/dockerd/docker.go:29 +0x54
Mar 10 15:17:17 raspberrypi dockerd[3300]: github.com/docker/docker/vendor/github.com/spf13/cobra.(*Command).execute(0x13982140, 0x1349e108, 0x2, 0x3, 0x13982140, 0x134
Mar 10 15:17:17 raspberrypi dockerd[3300]:         /go/src/github.com/docker/docker/vendor/github.com/spf13/cobra/command.go:762 +0x364
Mar 10 15:17:17 raspberrypi dockerd[3300]: github.com/docker/docker/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x13982140, 0x245c5a0, 0x21caaa0, 0x245c5a8)
Mar 10 15:17:17 raspberrypi dockerd[3300]:         /go/src/github.com/docker/docker/vendor/github.com/spf13/cobra/command.go:852 +0x220
Mar 10 15:17:17 raspberrypi dockerd[3300]: github.com/docker/docker/vendor/github.com/spf13/cobra.(*Command).Execute(0x13982140, 0x1349c0f0, 0x1)
Mar 10 15:17:17 raspberrypi dockerd[3300]:         /go/src/github.com/docker/docker/vendor/github.com/spf13/cobra/command.go:800 +0x1c
Mar 10 15:17:17 raspberrypi dockerd[3300]: main.main()
Mar 10 15:17:17 raspberrypi dockerd[3300]:         /go/src/github.com/docker/docker/cmd/dockerd/docker.go:70 +0x90
Mar 10 15:17:17 raspberrypi systemd[1]: Failed to start Docker Application Container Engine.
-- Subject: Unit docker.service has failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- Unit docker.service has failed.
-- 
-- The result is failed.
Mar 10 15:17:17 raspberrypi systemd[1]: docker.service: Unit entered failed state.
Mar 10 15:17:17 raspberrypi systemd[1]: docker.service: Failed with result 'exit-code'.
Mar 10 15:17:19 raspberrypi systemd[1]: docker.service: Service hold-off time over, scheduling restart.
Mar 10 15:17:19 raspberrypi systemd[1]: Stopped Docker Application Container Engine.
-- Subject: Unit docker.service has finished shutting down
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- Unit docker.service has finished shutting down.
Mar 10 15:17:19 raspberrypi systemd[1]: docker.service: Start request repeated too quickly.
Mar 10 15:17:19 raspberrypi systemd[1]: Failed to start Docker Application Container Engine.
-- Subject: Unit docker.service has failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- Unit docker.service has failed.
-- 
-- The result is failed.
Mar 10 15:17:19 raspberrypi systemd[1]: docker.service: Unit entered failed state.
Mar 10 15:17:19 raspberrypi systemd[1]: docker.service: Failed with result 'exit-code'.
```

**Comment by JackoPR1** [comment]
docker version
```
Client:
 Version:           18.09.0
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        4d60db4
 Built:             Wed Nov  7 00:57:21 2018
 OS/Arch:           linux/arm
 Experimental:      false
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

**Comment by JackoPR1** [comment]
@thaJeztah :: Do you mind taking a look at my issue if you get a moment?

**Comment by Eskyee** [comment]
@JackoPR1    done this in root as I had the same error as above!!

systemctl start docker 
cd BTCPayServer

#fresh install
git clone https://github.com/btcpayserver/btcpayserver-docker
cd btcpayserver-docker

export BTCPAY_HOST="btcpay.YourDomain.com"
export LETSENCRYPT_EMAIL=me@example.com
export ACME_CA_URI=https://acme-v01.api.letsencrypt.org/directory
export NBITCOIN_NETWORK="mainnet"
export BTCPAYGEN_CRYPTO1="btc"
export BTCPAYGEN_REVERSEPROXY="nginx"
export BTCPAYGEN_LIGHTNING="lnd"
export BTCPAYGEN_ADDITIONAL_FRAGMENTS="opt-save-storage-xs;opt-save-memory

 . ./btcpay-setup.sh -I

exit


now working!! on my raspberry

**Comment by NicolasDorier** [comment]
@Eskyee what made it works?

**Comment by Eskyee** [comment]
systemctl start docker
This got me working Nicolas 
After I found this error

**Comment by JackoPR1** [comment]
@Eskyee what version of docker-ce do you have installed. since system updating I just get this error
`Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?`

to replicate my issue try first removing docker-ce, then install btcpayserver
`sudo apt-get purge docker-ce && apt autoremove`

**Comment by Eskyee** [comment]
docker version
Client:
 Version:           18.09.0
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        4d60db4
 Built:             Wed Nov  7 00:57:21 2018
 OS/Arch:           linux/arm
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.0
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       4d60db4
  Built:            Wed Nov  7 00:17:57 2018
  OS/Arch:          linux/arm
  Experimental:     false

**Comment by JackoPR1** [comment]
I do not want to delete my existing containers nor volumes. 
running dockerd -D
```
DEBU[2019-03-11T10:58:57.935663724-04:00] Listener created for HTTP on unix (/var/run/docker.sock) 
DEBU[2019-03-11T10:58:57.949800867-04:00] Golang's threads limit set to 13860          
INFO[2019-03-11T10:58:57.951530705-04:00] parsed scheme: "unix"                         module=grpc
INFO[2019-03-11T10:58:57.951633257-04:00] scheme "unix" not registered, fallback to default scheme  module=grpc
INFO[2019-03-11T10:58:57.951919662-04:00] parsed scheme: "unix"                         module=grpc
INFO[2019-03-11T10:58:57.951983203-04:00] scheme "unix" not registered, fallback to default scheme  module=grpc
INFO[2019-03-11T10:58:57.952397056-04:00] ccResolverWrapper: sending new addresses to cc: [{unix:///run/containerd/containerd.sock 0  <nil>}]  module=grpc
DEBU[2019-03-11T10:58:57.952513670-04:00] Using default logging driver json-file       
INFO[2019-03-11T10:58:57.952533462-04:00] ClientConn switching balancer to "pick_first"  module=grpc
INFO[2019-03-11T10:58:57.952657993-04:00] ccResolverWrapper: sending new addresses to cc: [{unix:///run/containerd/containerd.sock 0  <nil>}]  module=grpc
INFO[2019-03-11T10:58:57.952740805-04:00] ClientConn switching balancer to "pick_first"  module=grpc
INFO[2019-03-11T10:58:57.952930232-04:00] pickfirstBalancer: HandleSubConnStateChange: 0x13e38220, CONNECTING  module=grpc
DEBU[2019-03-11T10:58:57.953056169-04:00] [graphdriver] priority list: [btrfs zfs overlay2 aufs overlay devicemapper vfs] 
INFO[2019-03-11T10:58:57.952705805-04:00] pickfirstBalancer: HandleSubConnStateChange: 0x14298240, CONNECTING  module=grpc
INFO[2019-03-11T10:58:57.956643136-04:00] pickfirstBalancer: HandleSubConnStateChange: 0x14298240, READY  module=grpc
INFO[2019-03-11T10:58:57.958194538-04:00] pickfirstBalancer: HandleSubConnStateChange: 0x13e38220, READY  module=grpc
DEBU[2019-03-11T10:58:57.958682349-04:00] processing event stream                       module=libcontainerd namespace=plugins.moby
DEBU[2019-03-11T10:58:57.966975603-04:00] backingFs=extfs,  projectQuotaSupported=false  storage-driver=overlay2
INFO[2019-03-11T10:58:57.967111644-04:00] [graphdriver] using prior storage driver: overlay2 
DEBU[2019-03-11T10:58:57.967196540-04:00] Initialized graph driver overlay2            
INFO[2019-03-11T10:59:01.164353515-04:00] Graph migration to content-addressability took 0.00 seconds 
WARN[2019-03-11T10:59:01.165976739-04:00] Your kernel does not support cgroup memory limit 
WARN[2019-03-11T10:59:01.166451424-04:00] Your kernel does not support cgroup cfs period 
WARN[2019-03-11T10:59:01.166801059-04:00] Your kernel does not support cgroup cfs quotas 
WARN[2019-03-11T10:59:01.167156526-04:00] Your kernel does not support cgroup rt period 
WARN[2019-03-11T10:59:01.167503036-04:00] Your kernel does not support cgroup rt runtime 
WARN[2019-03-11T10:59:01.168788084-04:00] mountpoint for pids not found                
DEBU[2019-03-11T10:59:01.170446776-04:00] Max Concurrent Downloads: 3                  
DEBU[2019-03-11T10:59:01.170567349-04:00] Max Concurrent Uploads: 5                    
INFO[2019-03-11T10:59:01.171439534-04:00] Loading containers: start.                   
DEBU[2019-03-11T10:59:01.172273854-04:00] processing event stream                       module=libcontainerd namespace=moby
DEBU[2019-03-11T10:59:01.183999702-04:00] Loaded container 07c823d8f855ed4ac925c78260a8270e4c03232c8db3ec90e4e9d0ab268bbd55, isRunning: false 
DEBU[2019-03-11T10:59:01.188268126-04:00] Loaded container 12f801929841787d90953d2743fcf35c0dabc7c50aaedbaf77f9820bbf3236d2, isRunning: false 
DEBU[2019-03-11T10:59:01.192304519-04:00] Loaded container 348197af1c4a5f4393cf193a19622d730bc28a5b0659148582e0e2e3365118ef, isRunning: false 
DEBU[2019-03-11T10:59:01.196860025-04:00] Loaded container 53142f6d17739639d7b8a8262a5e48ff2c3bd85b182e44c772f9f8c6bbd15244, isRunning: false 
DEBU[2019-03-11T10:59:01.201873603-04:00] Loaded container 7c44582a44d89f016f4e645429d4df3a0bc0180dd74a7e0505d584df95b7bc11, isRunning: false 
DEBU[2019-03-11T10:59:01.214677990-04:00] Loaded container adfbcc33ad8b49cea573c940f4114cb0e452f84e6c5163f738f504b3eb2cc494, isRunning: false 
DEBU[2019-03-11T10:59:01.224480927-04:00] Loaded container b9da12e3dfa6d7e34411532b6ebbe4a30e7845b39272027bf119dad1b64359da, isRunning: false 
DEBU[2019-03-11T10:59:01.233307670-04:00] Loaded container c521d485e94455a27816dab1d5395aa25712c3dd65b8f202e27e319bd28e2ddb, isRunning: false 
DEBU[2019-03-11T10:59:01.242677484-04:00] Loaded container cf7c45ed1b3f7867ec12254446a18f6211715fe30ffc937e359fa774714e5085, isRunning: false 
DEBU[2019-03-11T10:59:01.364347044-04:00] restoring container                           container=348197af1c4a5f4393cf193a19622d730bc28a5b0659148582e0e2e3365118ef paused=false running=false
DEBU[2019-03-11T10:59:01.364443398-04:00] restoring container                           container=cf7c45ed1b3f7867ec12254446a18f6211715fe30ffc937e359fa774714e5085 paused=false running=false
DEBU[2019-03-11T10:59:01.365096729-04:00] restoring container                           container=c521d485e94455a27816dab1d5395aa25712c3dd65b8f202e27e319bd28e2ddb paused=false running=false
DEBU[2019-03-11T10:59:01.381514020-04:00] restoring container                           container=7c44582a44d89f016f4e645429d4df3a0bc0180dd74a7e0505d584df95b7bc11 paused=false running=false
DEBU[2019-03-11T10:59:01.382167351-04:00] restoring container                           container=b9da12e3dfa6d7e34411532b6ebbe4a30e7845b39272027bf119dad1b64359da paused=false running=false
DEBU[2019-03-11T10:59:01.382255007-04:00] restoring container                           container=07c823d8f855ed4ac925c78260a8270e4c03232c8db3ec90e4e9d0ab268bbd55 paused=false running=false
DEBU[2019-03-11T10:59:01.382889745-04:00] restoring container                           container=adfbcc33ad8b49cea573c940f4114cb0e452f84e6c5163f738f504b3eb2cc494 paused=false running=false
DEBU[2019-03-11T10:59:01.388358998-04:00] restoring container                           container=53142f6d17739639d7b8a8262a5e48ff2c3bd85b182e44c772f9f8c6bbd15244 paused=false running=false
DEBU[2019-03-11T10:59:01.395203404-04:00] restoring container                           container=12f801929841787d90953d2743fcf35c0dabc7c50aaedbaf77f9820bbf3236d2 paused=false running=false
DEBU[2019-03-11T10:59:01.396735795-04:00] Option Experimental: false                   
DEBU[2019-03-11T10:59:01.396828346-04:00] Option DefaultDriver: bridge                 
DEBU[2019-03-11T10:59:01.396868346-04:00] Option DefaultNetwork: bridge                
DEBU[2019-03-11T10:59:01.396907252-04:00] Network Control Plane MTU: 1500              
DEBU[2019-03-11T10:59:01.438300245-04:00] /sbin/iptables, [--wait -t filter -C FORWARD -j DOCKER-ISOLATION] 
DEBU[2019-03-11T10:59:01.447276050-04:00] /sbin/iptables, [--wait -t nat -D PREROUTING -m addrtype --dst-type LOCAL -j DOCKER] 
DEBU[2019-03-11T10:59:01.456625656-04:00] /sbin/iptables, [--wait -t nat -D OUTPUT -m addrtype --dst-type LOCAL ! --dst 127.0.0.0/8 -j DOCKER] 
DEBU[2019-03-11T10:59:01.465653544-04:00] /sbin/iptables, [--wait -t nat -D OUTPUT -m addrtype --dst-type LOCAL -j DOCKER] 
DEBU[2019-03-11T10:59:01.474570494-04:00] /sbin/iptables, [--wait -t nat -D PREROUTING] 
DEBU[2019-03-11T10:59:01.483109061-04:00] /sbin/iptables, [--wait -t nat -D OUTPUT]    
DEBU[2019-03-11T10:59:01.493860954-04:00] /sbin/iptables, [--wait -t nat -F DOCKER]    
DEBU[2019-03-11T10:59:01.502622436-04:00] /sbin/iptables, [--wait -t nat -X DOCKER]    
DEBU[2019-03-11T10:59:01.511445064-04:00] /sbin/iptables, [--wait -t filter -F DOCKER] 
DEBU[2019-03-11T10:59:01.521158523-04:00] /sbin/iptables, [--wait -t filter -X DOCKER] 
DEBU[2019-03-11T10:59:01.530580107-04:00] /sbin/iptables, [--wait -t filter -F DOCKER-ISOLATION-STAGE-1] 
DEBU[2019-03-11T10:59:01.540215754-04:00] /sbin/iptables, [--wait -t filter -X DOCKER-ISOLATION-STAGE-1] 
DEBU[2019-03-11T10:59:01.549542651-04:00] /sbin/iptables, [--wait -t filter -F DOCKER-ISOLATION-STAGE-2] 
DEBU[2019-03-11T10:59:01.559014809-04:00] /sbin/iptables, [--wait -t filter -X DOCKER-ISOLATION-STAGE-2] 
DEBU[2019-03-11T10:59:01.568374414-04:00] /sbin/iptables, [--wait -t filter -F DOCKER-ISOLATION] 
DEBU[2019-03-11T10:59:01.577298604-04:00] /sbin/iptables, [--wait -t filter -X DOCKER-ISOLATION] 
DEBU[2019-03-11T10:59:01.586201284-04:00] /sbin/iptables, [--wait -t nat -n -L DOCKER] 
DEBU[2019-03-11T10:59:01.595352870-04:00] /sbin/iptables, [--wait -t nat -N DOCKER]    
DEBU[2019-03-11T10:59:01.604311591-04:00] /sbin/iptables, [--wait -t filter -n -L DOCKER] 
DEBU[2019-03-11T10:59:01.613508333-04:00] /sbin/iptables, [--wait -t filter -N DOCKER] 
DEBU[2019-03-11T10:59:01.623114500-04:00] /sbin/iptables, [--wait -t filter -n -L DOCKER-ISOLATION-STAGE-1] 
DEBU[2019-03-11T10:59:01.632227856-04:00] /sbin/iptables, [--wait -t filter -N DOCKER-ISOLATION-STAGE-1] 
DEBU[2019-03-11T10:59:01.641824961-04:00] /sbin/iptables, [--wait -t filter -n -L DOCKER-ISOLATION-STAGE-2] 
DEBU[2019-03-11T10:59:01.650864620-04:00] /sbin/iptables, [--wait -t filter -N DOCKER-ISOLATION-STAGE-2] 
DEBU[2019-03-11T10:59:01.660497506-04:00] /sbin/iptables, [--wait -t filter -C DOCKER-ISOLATION-STAGE-1 -j RETURN] 
DEBU[2019-03-11T10:59:01.669705445-04:00] /sbin/iptables, [--wait -A DOCKER-ISOLATION-STAGE-1 -j RETURN] 
DEBU[2019-03-11T10:59:01.679481768-04:00] /sbin/iptables, [--wait -t filter -C DOCKER-ISOLATION-STAGE-2 -j RETURN] 
DEBU[2019-03-11T10:59:01.688731791-04:00] /sbin/iptables, [--wait -A DOCKER-ISOLATION-STAGE-2 -j RETURN] 
DEBU[2019-03-11T10:59:01.702603309-04:00] Network (927f5cb) not found for restored bridge endpoint (671809e) 
DEBU[2019-03-11T10:59:01.703148828-04:00] Deleting stale bridge endpoint (671809e) from store 
INFO[2019-03-11T10:59:01.704250075-04:00] stopping event stream following graceful shutdown  error="context canceled" module=libcontainerd namespace=plugins.moby
INFO[2019-03-11T10:59:01.704353720-04:00] stopping event stream following graceful shutdown  error="context canceled" module=libcontainerd namespace=moby
panic: assertion failed: write: circular dependency occurred

goroutine 1 [running]:
github.com/docker/docker/vendor/go.etcd.io/bbolt._assert(0x145f5100, 0x1c01754, 0x23, 0x0, 0x0, 0x0)
	/go/src/github.com/docker/docker/vendor/go.etcd.io/bbolt/db.go:1136 +0xb8
github.com/docker/docker/vendor/go.etcd.io/bbolt.(*node).write(0x14206a80, 0x145f5000)
	/go/src/github.com/docker/docker/vendor/go.etcd.io/bbolt/node.go:226 +0x2f8
github.com/docker/docker/vendor/go.etcd.io/bbolt.(*node).spill(0x14206a80, 0x145eaee0, 0x1459cdac)
	/go/src/github.com/docker/docker/vendor/go.etcd.io/bbolt/node.go:378 +0x2dc
github.com/docker/docker/vendor/go.etcd.io/bbolt.(*Bucket).spill(0x145eaec0, 0x145eae00, 0x1459cf1c)
	/go/src/github.com/docker/docker/vendor/go.etcd.io/bbolt/bucket.go:568 +0x388
github.com/docker/docker/vendor/go.etcd.io/bbolt.(*Bucket).spill(0x1411f38c, 0xbf19bbcd, 0xe9f9be49)
	/go/src/github.com/docker/docker/vendor/go.etcd.io/bbolt/bucket.go:535 +0x2dc
github.com/docker/docker/vendor/go.etcd.io/bbolt.(*Tx).Commit(0x1411f380, 0x0, 0x0)
	/go/src/github.com/docker/docker/vendor/go.etcd.io/bbolt/tx.go:160 +0xbc
github.com/docker/docker/vendor/go.etcd.io/bbolt.(*DB).Update(0x143acfc0, 0x1459d028, 0x0, 0x0)
	/go/src/github.com/docker/docker/vendor/go.etcd.io/bbolt/db.go:677 +0xd4
github.com/docker/docker/vendor/github.com/docker/libkv/store/boltdb.(*BoltDB).AtomicDelete(0x14206740, 0x145e89a0, 0x65, 0x145eada0, 0x0, 0x0, 0x0)
	/go/src/github.com/docker/docker/vendor/github.com/docker/libkv/store/boltdb/boltdb.go:329 +0x120
github.com/docker/docker/vendor/github.com/docker/libnetwork/datastore.(*datastore).DeleteObjectAtomic(0x1451b950, 0x240dcc0, 0x1420f220, 0x0, 0x0)
	/go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/datastore/datastore.go:623 +0x1e4
github.com/docker/docker/vendor/github.com/docker/libnetwork/drivers/bridge.(*driver).storeDelete(0x1416c700, 0x240dcc0, 0x1420f220, 0x1, 0x1)
	/go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/drivers/bridge/bridge_store.go:120 +0x4c
github.com/docker/docker/vendor/github.com/docker/libnetwork/drivers/bridge.(*driver).populateEndpoints(0x1416c700, 0x0, 0x0)
	/go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/drivers/bridge/bridge_store.go:87 +0x3bc
github.com/docker/docker/vendor/github.com/docker/libnetwork/drivers/bridge.(*driver).initStore(0x1416c700, 0x145c95a0, 0x0, 0x1426d360)
	/go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/drivers/bridge/bridge_store.go:40 +0x184
github.com/docker/docker/vendor/github.com/docker/libnetwork/drivers/bridge.(*driver).configure(0x1416c700, 0x145c95a0, 0x0, 0x4000105)
	/go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/drivers/bridge/bridge.go:378 +0x170
github.com/docker/docker/vendor/github.com/docker/libnetwork/drivers/bridge.Init(0x23facb8, 0x145c9580, 0x145c95a0, 0x0, 0xffffffff)
	/go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/drivers/bridge/bridge.go:161 +0x90
github.com/docker/docker/vendor/github.com/docker/libnetwork/drvregistry.(*DrvRegistry).AddDriver(0x145c9580, 0x1bbfc62, 0x6, 0x23e9738, 0x145c95a0, 0x13d0fb18, 0x1)
	/go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/drvregistry/drvregistry.go:72 +0x38
github.com/docker/docker/vendor/github.com/docker/libnetwork.New(0x1416c680, 0x9, 0x10, 0x13e26990, 0x1455f340, 0x1416c680, 0x9)
	/go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/controller.go:220 +0x3bc
github.com/docker/docker/daemon.(*Daemon).initNetworkController(0x13d6c000, 0x143a8500, 0x1455f340, 0x13d6c000, 0x13d3c5e0, 0x1455f340, 0x1455f320)
	/go/src/github.com/docker/docker/daemon/daemon_unix.go:807 +0x6c
github.com/docker/docker/daemon.(*Daemon).restore(0x13d6c000, 0x143f42c0, 0x141800c0)
	/go/src/github.com/docker/docker/daemon/daemon.go:419 +0xa80
github.com/docker/docker/daemon.NewDaemon(0x2406748, 0x143f42c0, 0x143a8500, 0x13e26990, 0x0, 0x0, 0x0)
	/go/src/github.com/docker/docker/daemon/daemon.go:987 +0x249c
main.(*DaemonCli).start(0x14201160, 0x13e31b30, 0x0, 0x0)
	/go/src/github.com/docker/docker/cmd/dockerd/daemon.go:180 +0x614
main.runDaemon(0x13e31b30, 0x142a0300, 0x0)
	/go/src/github.com/docker/docker/cmd/dockerd/docker_unix.go:7 +0x34
main.newDaemonCommand.func1(0x143aa000, 0x13d0f3d8, 0x0, 0x1, 0x0, 0x0)
	/go/src/github.com/docker/docker/cmd/dockerd/docker.go:29 +0x54
github.com/docker/docker/vendor/github.com/spf13/cobra.(*Command).execute(0x143aa000, 0x13d0c058, 0x1, 0x1, 0x143aa000, 0x13d0c058)
	/go/src/github.com/docker/docker/vendor/github.com/spf13/cobra/command.go:762 +0x364
github.com/docker/docker/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x143aa000, 0x23ef5a0, 0x215daa0, 0x23ef5a8)
	/go/src/github.com/docker/docker/vendor/github.com/spf13/cobra/command.go:852 +0x220
github.com/docker/docker/vendor/github.com/spf13/cobra.(*Command).Execute(0x143aa000, 0x13d0e100, 0x1)
	/go/src/github.com/docker/docker/vendor/github.com/spf13/cobra/command.go:800 +0x1c
main.main()
	/go/src/github.com/docker/docker/cmd/dockerd/docker.go:70 +0x90
```

**Comment by Eskyee** [comment]
I can try to replicate your error tonight on a spare raspberry

**Comment by JackoPR1** [comment]
uname -a
`Linux raspberrypi 4.14.98-v7+ #1200 SMP Tue Feb 12 20:27:48 GMT 2019 armv7l GNU/Linux`
