### ISSUE TITLE
generated_btcpayserver_1 errors -> resulting in LND not working at all

### ISSUE THREAD

**Issue by maltokyo** [btcpayserver/btcpayserver-docker#205]
Suddenly a few days ago I couldn't connect to my node.  I was away, and not with the server, hence no changes at all happened in this time (it was working well for days after I left home).

Now LND (0.7.1) doesn't work at all, with the error below.  Should I upgrade?  I am afraid to upgrade in case it will break things further.

```
~# bitcoin-lncli.sh listchannels
[lncli] rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:10009: connect: connection refused"
```

**Comment by maltokyo** [comment]
Upon further investigation, looks like entire BTCPay Server node is down.  

Going to the main URL I get:

```
Your nodes are synching...
×
Your node is synching the entire blockchain and validating the consensus rules...

BTC
The node is offline
Last error: Response status code does not indicate success: 500 (Internal Server Error).
Watch this video to understand the importance of blockchain synchronization.

If you really don't want to synch and that you are familiar with command line, check FastSync.
```

**Comment by maltokyo** [comment]
Furthermore, the docker container btcpayserver itself seems to be the issue.

After a few mins after a restart, it shows these errors


```
~/BTCPayServer# docker logs generated_btcpayserver_1
info: Configuration:  Data Directory: /datadir
info: Configuration:  Configuration File: /datadir/Main/settings.config
info: Configuration:  Network: Mainnet
info: Configuration:  Supported chains: BTC
info: Configuration:  LogFile: btcpay.log
info: Configuration:  Log Level: Debug
info: Configuration:  Network: Mainnet
info: Configuration:  Supported chains: BTC
info: Configuration:  LogFile: btcpay.log
info: Configuration:  Log Level: Debug
info: Configuration:  Postgres DB used (User ID=postgres;Host=postgres;Port=5432;Database=btcpayservermainnet)
info: Configuration:  Root Path: /
info: Configuration:  BTC: Explorer url is http://nbxplorer:32838/
info: Configuration:  BTC: Cookie file is /root/.nbxplorer/Main/.cookie
info: PayServer:      Starting listening NBXplorer (BTC)
info: PayServer:      Start watching invoices
info: PayServer:      Starting payment request expiration watcher
info: Configuration:  Listening on http://0.0.0.0:49392
info: Events:         NBXplorer BTC: NotConnected => Synching
info: PayServer:      0 pending payment requests being checked since last run
fail: PayServer:      BTC: NBXplorer error `Response status code does not indicate success: 500 (Internal Server Error).`
info: Events:         NBXplorer BTC: Synching => NotConnected
fail: PayServer:      BTC: NBXplorer error `Response status code does not indicate success: 500 (Internal Server Error).`
info: Events:         NBXplorer BTC: NotConnected => Synching
fail: PayServer:      BTC: NBXplorer error `Response status code does not indicate success: 500 (Internal Server Error).`
info: Events:         NBXplorer BTC: Synching => NotConnected
fail: PayServer:      BTC: NBXplorer error `Response status code does not indicate success: 500 (Internal Server Error).`
info: Events:         NBXplorer BTC: NotConnected => Synching
fail: PayServer:      BTC: NBXplorer error `Response status code does not indicate success: 500 (Internal Server Error).`
info: Events:         NBXplorer BTC: Synching => NotConnected
fail: PayServer:      BTC: NBXplorer error `Response status code does not indicate success: 500 (Internal Server Error).`
info: Events:         NBXplorer BTC: NotConnected => Synching
fail: PayServer:      BTC: NBXplorer error `Response status code does not indicate success: 500 (Internal Server Error).`
info: Events:         NBXplorer BTC: Synching => NotConnected
fail: PayServer:      BTC: NBXplorer error `Response status code does not indicate success: 500 (Internal Server Error).`
info: Events:         NBXplorer BTC: NotConnected => Synching
fail: PayServer:      BTC: NBXplorer error `Response status code does not indicate success: 500 (Internal Server Error).`
info: Events:         NBXplorer BTC: Synching => NotConnected
fail: PayServer:      BTC: NBXplorer error `Response status code does not indicate success: 500 (Internal Server Error).`
info: Events:         NBXplorer BTC: NotConnected => Synching
fail: PayServer:      BTC: NBXplorer error `Response status code does not indicate success: 500 (Internal Server Error).`
info: Events:         NBXplorer BTC: Synching => NotConnected
fail: PayServer:      BTC: NBXplorer error `Response status code does not indicate success: 500 (Internal Server Error).`
info: Events:         NBXplorer BTC: NotConnected => Synching
```

**Comment by maltokyo** [comment]
On another error it said it is due to RAM issues.  I have 16GB, and plenty left

```
~/BTCPayServer# free -h
              total        used        free      shared  buff/cache   available
Mem:            15G        896M        8.9G         14M        5.6G         14G
Swap:            0B          0B          0B
```

**Comment by maltokyo** [comment]
Running `docker logs --tail 10 btcpayserver_bitcoind` gives this..  how to recover?

```
~/BTCPayServer# docker logs --tail 10 btcpayserver_bitcoind
2019-10-13T20:50:28Z Pre-allocating up to position 0x5000000 in blk01819.dat
2019-10-13T20:50:29Z Pre-allocating up to position 0x6000000 in blk01819.dat
2019-10-13T20:50:29Z Pre-allocating up to position 0x7000000 in blk01819.dat
2019-10-13T20:50:31Z Pre-allocating up to position 0x8000000 in blk01819.dat
2019-10-13T20:50:31Z LevelDB read failure: Corruption: block checksum mismatch: /home/bitcoin/.bitcoin/chainstate/302363.ldb
2019-10-13T20:50:31Z Fatal LevelDB error: Corruption: block checksum mismatch: /home/bitcoin/.bitcoin/chainstate/302363.ldb
2019-10-13T20:50:31Z You can use -debug=leveldb to get more complete diagnostic messages
2019-10-13T20:50:31Z Error: Error reading from database, shutting down.
2019-10-13T20:50:31Z Error reading from database: Fatal LevelDB error: Corruption: block checksum mismatch: /home/bitcoin/.bitcoin/chainstate/302363.ldb
Error: Error reading from database, shutting down.
```

**Comment by maltokyo** [comment]
Hi @NicolasDorier - would it be better just to delete the entire blockchain _data dir and ask it to resync again (for a week ;( ) ?  Your advice would be great.

**Comment by NicolasDorier** [comment]
@maltokyo ugh, yes this is a corruption. This does not happen very often, but seems to be your problem.

Can you check if you don't run out of disk space with `df -h` ?

**Comment by maltokyo** [comment]
@NicolasDorier thanks for reply!  The disk is no issue, I have dedicated 500GB drive for BTCPay Server, `/dev/sdb1` as in last line below.  It has been running for months on this disk without issue.  So I should delete entire bitcoin _data dir and start sync again?  Do you know if there is some way just to "repair" bad blocks etc?

```
~# df -h
Filesystem      Size  Used Avail Use% Mounted on
udev            7.7G     0  7.7G   0% /dev
tmpfs           1.6G  2.1M  1.6G   1% /run
/dev/sda2       458G   35G  401G   8% /
tmpfs           7.7G     0  7.7G   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           7.7G     0  7.7G   0% /sys/fs/cgroup
/dev/loop0       90M   90M     0 100% /snap/core/7917
/dev/loop1       90M   90M     0 100% /snap/core/7713
/dev/sdb1       458G  285G  174G  63% /media/500gb_BTCPay
```

**Comment by NicolasDorier** [comment]
@maltokyo no you can't repair. That sucks for sure. :(

**Comment by maltokyo** [comment]
Thanks. Will sync again... sucks indeed.

**Comment by maltokyo** [comment]
OK, this is interesting.  I decided to run a hardware diagnostics from the bios menu of PC, and it showed that one of my RAM sticks was corrupted and failed the test.  This could have been the cause.  Started sync again after removing it, let's see.

**Comment by maltokyo** [comment]
@NicolasDorier i started all over again as above on a powerful pc. Now, it’s stuck at 99% for the last 7 hours.. I’m really lost. Bitcoind itself shows progress is finished on command line. But I can’t use BTCPayServer. Sorry for all the issues. 

![D32DEAF1-0EC0-4889-841F-6E9DE44F089F](https://user-images.githubusercontent.com/1388507/66831474-04e83c80-ef58-11e9-9015-0d1d4bd81187.png)

**Comment by maltokyo** [comment]
All logs seem fine, EXCEPT this one from `docker logs generated_nbxplorer_1`
Any help appreciated.

```
info: Configuration:  BTC: Loading chain from cache...
fail: Configuration:  BTC: Unhandled in Waiter loop
System.ArgumentException: newTip should be different from previous
   at NBitcoin.SlimChain.TrySetTipNoLock(uint256& newTip, uint256& previous, Boolean nopIfContainsTip)
   at NBitcoin.SlimChain.Load(Stream input)
   at NBXplorer.BitcoinDWaiter.LoadChainFromCache() in /source/NBXplorer/BitcoinDWaiter.cs:line 634
   at NBXplorer.BitcoinDWaiter.ConnectToBitcoinD(CancellationToken cancellation) in /source/NBXplorer/BitcoinDWaiter.cs:line 411
   at NBXplorer.BitcoinDWaiter.StepAsync(CancellationToken token) in /source/NBXplorer/BitcoinDWaiter.cs:line 310
   at NBXplorer.BitcoinDWaiter.StartLoop(CancellationToken token, Signaler tick) in /source/NBXplorer/BitcoinDWaiter.cs:line 195
info: Configuration:  BTC: Testing again in 60 seconds
```

**Comment by NicolasDorier** [comment]
Closing this as now it is solved.
