### ISSUE TITLE
nbxplorer failing with "fail: Configuration:  BTC: Unhandled in Waiter loop System.ArgumentException: newTip should be different from previous"

### ISSUE THREAD

**Issue by maltokyo** [btcpayserver/btcpayserver-docker#206]
I am making a new issue from #205 @NicolasDorier as I think it could be a different (bug?)

All logs seem fine, EXCEPT this one from `docker logs generated_nbxplorer_1`
Any help appreciated.

```
info: Configuration:  BTC: Loading chain from cache...
fail: Configuration:  BTC: Unhandled in Waiter loop
System.ArgumentException: newTip should be different from previous
   at NBitcoin.SlimChain.TrySetTipNoLock(uint256& newTip, uint256& previous, Boolean nopIfContainsTip)
   at NBitcoin.SlimChain.Load(Stream input)
   at NBXplorer.BitcoinDWaiter.LoadChainFromCache() in /source/NBXplorer/BitcoinDWaiter.cs:line 634
   at NBXplorer.BitcoinDWaiter.ConnectToBitcoinD(CancellationToken cancellation) in /source/NBXplorer/BitcoinDWaiter.cs:line 411
   at NBXplorer.BitcoinDWaiter.StepAsync(CancellationToken token) in /source/NBXplorer/BitcoinDWaiter.cs:line 310
   at NBXplorer.BitcoinDWaiter.StartLoop(CancellationToken token, Signaler tick) in /source/NBXplorer/BitcoinDWaiter.cs:line 195
info: Configuration:  BTC: Testing again in 60 seconds
```

**Comment by maltokyo** [comment]
Will try to delete NBXplorder _data dir and setup again...  maybe this will help.  What a pain

**Comment by maltokyo** [comment]
This: `delete NBXplorder _data dir` worked.  All running again, I guess that folder was also corrupted.

**Comment by NicolasDorier** [comment]
@maltokyo thanks. A corruption at this point should not break nbxplorer. Will push something to ignore it next time.

**Comment by GraemeConradie** [comment]
`xoxoxo@earth:/mnt/Nodes/NBXplorer$ ./run.sh
info: Configuration:  Data Directory: /home/xoxoxo/.nbxplorer/Main
info: Configuration:  Configuration File: /home/xoxoxo/.nbxplorer/Main/settings.config
info: Configuration:  Network: Mainnet
info: Configuration:  Supported chains: BTC
info: Configuration:  Network: Mainnet
info: Configuration:  Supported chains: BTC
info: Configuration:  BTC: Testing RPC connection to http://127.0.0.1:8332/
info: Configuration:  BTC: RPC connection successful
Hosting environment: Production
Content root path: /mnt/Nodes/NBXplorer/NBXplorer/bin/Release/netcoreapp3.1/
Now listening on: http://127.0.0.1:24444
Application started. Press Ctrl+C to shut down.
info: Configuration:  BTC: Full node version detected: 210000
info: Configuration:  BTC: Node banlist loaded
info: Configuration:  BTC: Trying to connect via the P2P protocol to trusted node (127.0.0.1:8333)...
info: Explorer:       BTC: TCP Connection succeed, handshaking...
info: Explorer:       BTC: Handshaked
info: Configuration:  BTC: Loading chain from node
info: Explorer:       BTC: Loading chain...
info: Explorer:       BTC: Chain loaded
fail: Configuration:  BTC: Unhandled in Waiter loop
System.ArgumentNullException: Value cannot be null. (Parameter 'value')
   at Newtonsoft.Json.Linq.JToken.EnsureValue(JToken value)
   at Newtonsoft.Json.Linq.JToken.op_Explicit(JToken value)
   at NBitcoin.RPC.RPCClient.GetPeersInfoAsync()
   at NBXplorer.BitcoinDWaiter.ConnectToBitcoinD(CancellationToken cancellation) in /mnt/Nodes/NBXplorer/NBXplorer/BitcoinDWaiter.cs:line 470
   at NBXplorer.BitcoinDWaiter.StepAsync(CancellationToken token) in /mnt/Nodes/NBXplorer/NBXplorer/BitcoinDWaiter.cs:line 300
   at NBXplorer.BitcoinDWaiter.StartLoop(CancellationToken token, Signaler tick) in /mnt/Nodes/NBXplorer/NBXplorer/BitcoinDWaiter.cs:line 196
info: Configuration:  BTC: Testing again in 5 seconds
^CApplication is shutting down...
`
@maltokyo Where is the _data dir that you deleted, I cannot see a folder that looks like a data folder ?

**Comment by GraemeConradie** [comment]
@maltokyo you mean the BTC Blockchain Data folder ? Nothing wrong with my chain. I am not hooking into a container here, I am directly connecting to my fullnode on 8332.

"fail: Configuration:  BTC: Unhandled in Waiter loop"

**Comment by maltokyo** [comment]
In The docker volume directory. Inside the NBX dir you'll see one called _data

**Comment by maltokyo** [comment]
Usually that's inside /var/docker/volumes

**Comment by GraemeConradie** [comment]
@maltokyo I am not running inside a container.

**Comment by anarcat** [comment]
> @maltokyo thanks. A corruption at this point should not break nbxplorer. Will push something to ignore it next time.

i just had this problem on a server that ran out of disk space, it seems this problem is still not fixed.
