### ISSUE TITLE
YamlDotNet.Core.SemanticErrorException Errors when running btcpay-update.sh and btcpay-setup.sh

### ISSUE THREAD

**Issue by maltokyo** [btcpayserver/btcpayserver-docker#220]
I tried to run `btcpay-setup.sh` and got below error, so I tried to upgrade to see if it fixes it using `btcpay-update.sh`, and got the same error again (was already on the latest version)

```
:~/BTCPayServer/btcpayserver-docker# ./btcpay-update.sh 
Already up to date.
Using default tag: latest
latest: Pulling from btcpayserver/docker-compose-generator
Digest: sha256:5d4e2f40934b1cdcfbd05eb329f263edd8c02c0038566fe8fbe5074553a892aa
Status: Image is up to date for btcpayserver/docker-compose-generator:latest
docker.io/btcpayserver/docker-compose-generator:latest
Crypto: btc
Lightning: lnd
ReverseProxy: nginx
Generating /app/Generated/docker-compose.generated.yml
With fragments:
	nginx-https
	nginx
	btcpayserver-nginx
	btcpayserver
	opt-add-tor
	nbxplorer
	postgres
	bitcoin
	opt-z-bitcoin-lnd.custom
	opt-z-bitcoin.custom
	opt-more-memory
	opt-expose-unsafe
	opt-txindex

Unhandled Exception: YamlDotNet.Core.SemanticErrorException: (Line: 8, Col: 6, Idx: 107) - (Line: 8, Col: 6, Idx: 107): While parsing a block mapping, did not find expected key.
   at YamlDotNet.Core.Parser.ParseBlockMappingKey(Boolean isFirst)
   at YamlDotNet.Core.Parser.StateMachine()
   at YamlDotNet.Core.Parser.MoveNext()
   at YamlDotNet.Core.ParserExtensions.Allow[T](IParser parser)
   at YamlDotNet.Core.ParserExtensions.Expect[T](IParser parser)
   at YamlDotNet.RepresentationModel.YamlSequenceNode.Load(IParser parser, DocumentLoadingState state)
   at YamlDotNet.RepresentationModel.YamlSequenceNode..ctor(IParser parser, DocumentLoadingState state)
   at YamlDotNet.RepresentationModel.YamlNode.ParseNode(IParser parser, DocumentLoadingState state)
   at YamlDotNet.RepresentationModel.YamlMappingNode.Load(IParser parser, DocumentLoadingState state)
   at YamlDotNet.RepresentationModel.YamlMappingNode..ctor(IParser parser, DocumentLoadingState state)
   at YamlDotNet.RepresentationModel.YamlNode.ParseNode(IParser parser, DocumentLoadingState state)
   at YamlDotNet.RepresentationModel.YamlMappingNode.Load(IParser parser, DocumentLoadingState state)
   at YamlDotNet.RepresentationModel.YamlMappingNode..ctor(IParser parser, DocumentLoadingState state)
   at YamlDotNet.RepresentationModel.YamlNode.ParseNode(IParser parser, DocumentLoadingState state)
   at YamlDotNet.RepresentationModel.YamlMappingNode.Load(IParser parser, DocumentLoadingState state)
   at YamlDotNet.RepresentationModel.YamlMappingNode..ctor(IParser parser, DocumentLoadingState state)
   at YamlDotNet.RepresentationModel.YamlNode.ParseNode(IParser parser, DocumentLoadingState state)
   at YamlDotNet.RepresentationModel.YamlDocument..ctor(IParser parser)
   at YamlDotNet.RepresentationModel.YamlStream.Load(IParser parser)
   at YamlDotNet.RepresentationModel.YamlStream.Load(TextReader input)
   at DockerGenerator.DockerComposeDefinition.ParseDocument(String fragment) in /source/DockerComposeDefinition.cs:line 200
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at DockerGenerator.DockerComposeDefinition.Build() in /source/DockerComposeDefinition.cs:line 67
   at DockerGenerator.Program.Main(String[] args) in /source/Program.cs:line 26
```

**Comment by NicolasDorier** [comment]
Probably mean your

```
	opt-z-bitcoin-lnd.custom
	opt-z-bitcoin.custom
```
are not proper yaml files. Please pass them through a validator.

**Comment by maltokyo** [comment]
Indeed, was my fault.  Sorry for stupid shit. Closing.
