### ISSUE TITLE
Update fails with an System.IO.FileNotFoundException: 

### ISSUE THREAD

**Issue by Amacruz** [btcpayserver/btcpayserver-docker#229]
Hello!

I tried to update recently and I received the error below. Tried re-starting, re-updating... nada. Still on version v1.0.3.135.

Generating /app/Generated/docker-compose.generated.yml

Unhandled Exception: System.IO.FileNotFoundException: Could not find file '/app/docker-fragments/btcpaygen_additional_fragments.yml'.
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding)
   at System.IO.File.ReadAllText(String path)
   at DockerGenerator.DockerComposeDefinition.ParseDocument(FragmentName fragment) in /source/DockerComposeDefinition.cs:line 257
   at DockerGenerator.DockerComposeDefinition.<>c__DisplayClass20_0.<Build>b__5(FragmentName f) in /source/DockerComposeDefinition.cs:line 71
   at System.Linq.Enumerable.SelectEnumerableIterator2.ToList()
   at DockerGenerator.DockerComposeDefinition.Build() in /source/DockerComposeDefinition.cs:line 71
   at DockerGenerator.Program.Main(String[] args) in /source/Program.cs:line 27
Failed to generate the docker-compose

**Comment by NicolasDorier** [comment]
I guess you fucked up one of your environment variables.

You probably wanted to change `$BTCPAYSERVER_ADDITIONAL_FRAGMENTS` and fucked it up.

Check its value with `echo $BTCPAYSERVER_ADDITIONAL_FRAGMENTS`

**Comment by Amacruz** [comment]
I guess I must have somehow! Here's what I get:

#echo $BTCPAYGEN_ADDITIONAL_FRAGMENTS
#BTCPAYGEN_ADDITIONAL_FRAGMENTS;opt-lnd-autopilot;opt-add-tor;opt-add-woocommerce;opt-add-btctransmuter;opt-lnd-autopilot;opt-lnd-autopilot;opt-add-woocommerce;opt-add-tor;opt-add-btctransmuter;opt-add-electrumx

Some variables are duplicated. All I added before the update was the electrumx. I thought the variables were non-recursive. How to I repair this now?

**Comment by NicolasDorier** [comment]
@Amacruz you can see that you have `BTCPAYGEN_ADDITIONAL_FRAGMENTS` as a string in the list, remove that.

`BTCPAYGEN_ADDITIONAL_FRAGMENTS=`opt-lnd-autopilot;opt-add-tor;opt-add-woocommerce;opt-add-btctransmuter;opt-lnd-autopilot;opt-lnd-autopilot;opt-add-woocommerce;opt-add-tor;opt-add-btctransmuter;opt-add-electrumx`

**Comment by NicolasDorier** [comment]
You have dups because instead of running

```
BTCPAYGEN_ADDITIONAL_FRAGMENTS="$BTCPAYGEN_ADDITIONAL_FRAGMENTS;opt-add-electrumx"
```

you ran

```
BTCPAYGEN_ADDITIONAL_FRAGMENTS="BTCPAYGEN_ADDITIONAL_FRAGMENTS;opt-add-electrumx"
```
