### ISSUE TITLE
Error updating: Could not find file '/app/docker-fragments/opt-less-memory.yml'

### ISSUE THREAD

**Issue by heelhook** [btcpayserver/btcpayserver-docker#241]
I'm getting this error when updating my instance of btcpayserver:

Any ideas?

Thanks!

```bash
# ./btcpay-update.sh
Already up to date.
Using default tag: latest
latest: Pulling from btcpayserver/docker-compose-generator
Digest: sha256:fe31e4b5e9a270021974558c25edc0cf5f1c967a894354e2283c289992a7b11c
Status: Image is up to date for btcpayserver/docker-compose-generator:latest
docker.io/btcpayserver/docker-compose-generator:latest
Crypto: btc
Lightning: lnd
ReverseProxy: nginx
Generating /app/Generated/docker-compose.generated.yml

Unhandled Exception: System.IO.FileNotFoundException: Could not find file '/app/docker-fragments/opt-less-memory.yml'.
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding)
   at System.IO.File.ReadAllText(String path)
   at DockerGenerator.DockerComposeDefinition.ParseDocument(FragmentName fragment) in /source/DockerComposeDefinition.cs:line 273
   at DockerGenerator.DockerComposeDefinition.<>c__DisplayClass20_0.<Build>b__9(FragmentName f) in /source/DockerComposeDefinition.cs:line 72
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToList()
   at DockerGenerator.DockerComposeDefinition.Build() in /source/DockerComposeDefinition.cs:line 72
   at DockerGenerator.Program.Main(String[] args) in /source/Program.cs:line 27
Failed to generate the docker-compose
```

**Comment by NicolasDorier** [comment]
Will fix the error message, but you use `opt-less-memory` instead of `opt-save-memory`
