### ISSUE TITLE
Unable to run btcpay-setup.sh: Access to the path '/app/crypto-definitions.json' is denied.

### ISSUE THREAD

**Issue by mr-e-** [btcpayserver/btcpayserver-docker#262]
Using default tag: latest
latest: Pulling from btcpayserver/docker-compose-generator
Digest: sha256:9f90dfe2abf4f9f4d3b1184349ad08237548dfb9a7098ff704d887500c8746ff
Status: Image is up to date for btcpayserver/docker-compose-generator:latest
docker.io/btcpayserver/docker-compose-generator:latest
Crypto: btc
Lightning: lnd
ReverseProxy: nginx
Unhandled exception. System.UnauthorizedAccessException: Access to the path '/app/crypto-definitions.json' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding)
   at System.IO.File.ReadAllText(String path)
   at DockerGenerator.Program.Run(DockerComposition composition, String name, String output) in /source/Program.cs:line 39
   at DockerGenerator.Program.Main(String[] args) in /source/Program.cs:line 28
Failed to generate the docker-compose

**Comment by Kukks** [comment]
did you `git pull` to the latest master branch?

**Comment by NicolasDorier** [comment]
Don't run `git pull`, run `btcpay-update.sh` first.

**Comment by mr-e-** [comment]
Yes I did. Turns out this is a potential issue with ubuntu for windows volume mounting.

I found the answer hidden deep on some forums to this article:
https://nickjanetakis.com/blog/setting-up-docker-for-windows-and-wsl-to-work-flawlessly

Specifically this tiny part:

Create and modify the new WSL configuration file:
sudo nano /etc/wsl.conf

# Now make it look like this and save the file when you're done:
[automount]
root = /
options = "metadata"
We need to set root = / because this will make your drives mounted at /c or /e instead of /mnt/c or /mnt/e.

**Comment by NicolasDorier** [comment]
TIL that docker could even work on WSL
