### ISSUE TITLE
Issue with tokens and/or Unauthorized access to the API

### ISSUE THREAD

**Issue by losterman** [btcpayserver/btcpayserver-docker#265]
Hi

Have setup with docker. Everything started working fine. But - upon running in a real mode with real funds met couple issues:

1) The log file is full of records:
--------------------------------------------------
2020-02-06 00:06:46.302 +00:00 [WRN] Error while contacting coinaverage: Unauthorized access to the API, premium plan needed
2020-02-06 00:07:17.049 +00:00 [WRN] Error while contacting coinaverage: Unauthorized access to the API, premium plan needed
2020-02-06 00:07:47.936 +00:00 [WRN] Error while contacting coinaverage: Unauthorized access to the API, premium plan needed
2020-02-06 00:08:18.872 +00:00 [WRN] Error while contacting coinaverage: Unauthorized access to the API, premium plan needed
2020-02-06 00:08:25.789 +00:00 [INF] BTC: New block
2020-02-06 00:08:50.716 +00:00 [WRN] Error while contacting coinaverage: Unauthorized access to the API, premium plan needed
2020-02-06 00:09:21.652 +00:00 [WRN] Error while contacting coinaverage: Unauthorized access to the API, premium plan needed
2020-02-06 00:09:54.788 +00:00 [WRN] Error while contacting coinaverage: Unauthorized access to the API, premium plan needed
2020-02-06 00:10:26.238 +00:00 [WRN] Error while contacting coinaverage: Unauthorized access to the API, premium plan needed
2020-02-06 00:10:56.963 +00:00 [WRN] Error while contacting coinaverage: Unauthorized access to the API, premium plan needed
2020-02-06 00:11:27.999 +00:00 [WRN] Error while contacting coinaverage: Unauthorized access to the API, premium plan needed
2020-02-06 00:11:59.123 +00:00 [WRN] Error while contacting coinaverage: Unauthorized access to the API, premium plan needed
2020-02-06 00:12:30.157 +00:00 [WRN] Error while contacting coinaverage: Unauthorized access to the API, premium plan needed
2020-02-06 00:13:01.701 +00:00 [WRN] Error while contacting coinaverage: Unauthorized access to the API, premium plan needed
2020-02-06 00:20:55.873 +00:00 [INF] BTC: New block
2020-02-06 00:28:35.426 +00:00 [WRN] Error while contacting coinaverage: Unauthorized access to the API, premium plan needed
2020-02-06 00:29:06.161 +00:00 [WRN] Error while contacting coinaverage: Unauthorized access to the API, premium plan needed
2020-02-06 00:29:38.705 +00:00 [WRN] Error while contacting coinaverage: Unauthorized access to the API, premium plan needed
2020-02-06 00:29:59.768 +00:00 [INF] BTC: New block
-------------------------------------------------------

2) May be depending on the (1) issue, but still - have setup token for the API - it works fine, but in some time (1 hour / 1 day / occasionally ) it stops working giving the result:
-------------------------------------------------------
Warning: No wallet has been linked to your BTCPay Store. See the following link for more information on how to connect your store and wallet. (https://docs.btcpayserver.org/getting-started/connectwallet) 2/6/20 4:11:34 PM: Creation of invoice starting 2/6/20 4:11:35 PM: BTC_USD: The rating rule is coinaverage(BTC_USD) 2/6/20 4:11:35 PM: BTC_USD: The evaluated rating rule is ERR_RATE_UNAVAILABLE(coinaverage, BTC_USD) 2/6/20 4:11:35 PM: BTC_USD: Rate rule error (RateUnavailable) 2/6/20 4:11:35 PM: BTC_USD: Exception reaching exchange coinaverage (Unauthorized access to the API, premium plan needed) 
------------------------------------------------------- 

Here it says: Warning: No wallet has been linked to your BTCPay Store.
But the wallet is linked for sure.
If I recreating token for the store - it still works for some time and the situation repeats.

So in total - the installed stuff works - but not usable for production ;(

Please advise of any ideas.

**Comment by losterman** [comment]
And some more logs content:
-------------------------------------------------
oinaverage: Unauthorized access to the API, premium plan needed
2020-02-06 00:46:16.585 +00:00 [WRN] GetRatesAsync was called on coinaverage when the rate is outdated. It should never happen, let BTCPayServer developers know about this.
2020-02-06 00:46:16.692 +00:00 [ERR] Connection id "0HLT8HOCAK4DC", Request id "0HLT8HOCAK4DC:00000001": An unhandled exception was thrown by the application.
System.InvalidOperationException: OnStarting cannot be set because the response has already started.
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ThrowResponseAlreadyStartedException(String value)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.OnStarting(Func`2 callback, Object state)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.Microsoft.AspNetCore.Http.Features.IHttpResponseFeature.OnStarting(Func`2 callback, Object state)
   at Microsoft.AspNetCore.Http.Internal.DefaultHttpResponse.OnStarting(Func`2 callback, Object state)
   at Microsoft.AspNetCore.Session.SessionMiddleware.SessionEstablisher..ctor(HttpContext context, String cookieValue, SessionOptions options)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
   at BTCPayServer.Hosting.BTCPayMiddleware.Invoke(HttpContext httpContext) in /source/BTCPayServer/Hosting/BTCpayMiddleware.cs:line 75
   at BTCPayServer.Hosting.HeadersOverrideMiddleware.Invoke(HttpContext httpContext) in /source/BTCPayServer/Hosting/HeadersOverrideMiddleware.cs:line 31
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
2020-02-06 00:46:17.912 +00:00 [WRN] Error while contacting coinaverage: Unauthorized access to the API, premium plan needed
2020-02-06 00:46:17.923 +00:00 [WRN] GetRatesAsync was called on coinaverage when the rate is outdated. It should never happen, let BTCPayServer developers know about this.
2020-02-06 00:46:18.026 +00:00 [ERR] Connection id "0HLT8HOCAK4DD", Request id "0HLT8HOCAK4DD:00000001": An unhandled exception was thrown by the application.
System.InvalidOperationException: OnStarting cannot be set because the response has already started.
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ThrowResponseAlreadyStartedException(String value)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.OnStarting(Func`2 callback, Object state)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.Microsoft.AspNetCore.Http.Features.IHttpResponseFeature.OnStarting(Func`2 callback, Object state)
   at Microsoft.AspNetCore.Http.Internal.DefaultHttpResponse.OnStarting(Func`2 callback, Object state)
   at Microsoft.AspNetCore.Session.SessionMiddleware.SessionEstablisher..ctor(HttpContext context, String cookieValue, SessionOptions options)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
   at BTCPayServer.Hosting.BTCPayMiddleware.Invoke(HttpContext httpContext) in /source/BTCPayServer/Hosting/BTCpayMiddleware.cs:line 75
   at BTCPayServer.Hosting.HeadersOverrideMiddleware.Invoke(HttpContext httpContext) in /source/BTCPayServer/Hosting/HeadersOverrideMiddleware.cs:line 31
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
2020-02-06 00:46:19.269 +00:00 [WRN] GetRatesAsync was called on coinaverage when the rate is outdated. It should never happen, let BTCPayServer developers know about this.
2020-02-06 00:46:19.374 +00:00 [ERR] Connection id "0HLT8HOCAK4DE", Request id "0HLT8HOCAK4DE:00000001": An unhandled exception was thrown by the application.
System.InvalidOperationException: OnStarting cannot be set because the response has already started.
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ThrowResponseAlreadyStartedException(String value)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.OnStarting(Func`2 callback, Object state)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.Microsoft.AspNetCore.Http.Features.IHttpResponseFeature.OnStarting(Func`2 callback, Object state)
   at Microsoft.AspNetCore.Http.Internal.DefaultHttpResponse.OnStarting(Func`2 callback, Object state)
   at Microsoft.AspNetCore.Session.SessionMiddleware.SessionEstablisher..ctor(HttpContext context, String cookieValue, SessionOptions options)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
   at BTCPayServer.Hosting.BTCPayMiddleware.Invoke(HttpContext httpContext) in /source/BTCPayServer/Hosting/BTCpayMiddleware.cs:line 75
   at BTCPayServer.Hosting.HeadersOverrideMiddleware.Invoke(HttpContext httpContext) in /source/BTCPayServer/Hosting/HeadersOverrideMiddleware.cs:line 31
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
2020-02-06 00:46:20.628 +00:00 [WRN] GetRatesAsync was called on coinaverage when the rate is outdated. It should never happen, let BTCPayServer developers know about this.
2020-02-06 00:46:20.733 +00:00 [ERR] Connection id "0HLT8HOCAK4DF", Request id "0HLT8HOCAK4DF:00000001": An unhandled exception was thrown by the application.
System.InvalidOperationException: OnStarting cannot be set because the response has already started.
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ThrowResponseAlreadyStartedException(String value)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.OnStarting(Func`2 callback, Object state)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.Microsoft.AspNetCore.Http.Features.IHttpResponseFeature.OnStarting(Func`2 callback, Object state)
   at Microsoft.AspNetCore.Http.Internal.DefaultHttpResponse.OnStarting(Func`2 callback, Object state)
   at Microsoft.AspNetCore.Session.SessionMiddleware.SessionEstablisher..ctor(HttpContext context, String cookieValue, SessionOptions options)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
   at BTCPayServer.Hosting.BTCPayMiddleware.Invoke(HttpContext httpContext) in /source/BTCPayServer/Hosting/BTCpayMiddleware.cs:line 75
   at BTCPayServer.Hosting.HeadersOverrideMiddleware.Invoke(HttpContext httpContext) in /source/BTCPayServer/Hosting/HeadersOverrideMiddleware.cs:line 31
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)

**Comment by britttttk** [comment]
Hey the issue is the exchange rate provider you are using, CoinAverage stopped offering their free service, you should choose a different rate provider in your store settings.

**Comment by losterman** [comment]
Hey
Thanks, looks like it should be updated more often than I dreamed about ;)
btcpay-update.sh looks to be a solution for the problem.
Is there a chance to setup my own exchange rate source ?

**Comment by NicolasDorier** [comment]
@losterman in your store's settings you have the Rate section to setup your own source.
