### ISSUE TITLE
lnd container problems after updating via script to v 0.11.0-beta

### ISSUE THREAD

**Issue by vanjaime** [btcpayserver/btcpayserver-docker#370]
Problems with lnd container after recent update to btcpayserver/lnd:v0.11.0-beta via btcpayupdate.sh
I had issues with nginx but after btcpay-restart.sh and btcpay-setup.sh -i 
I was able to connect again.

Here the log related to the lnd container:

```
LND_CHAIN=btc
LND_ENVIRONMENT=mainnet
Added bitcoin.active and bitcoin.mainnet to config file /data/lnd.conf
Waiting /root/.nbxplorer/btc_fully_synched to be created...
The chain is fully synched
Waiting /var/lib/tor/hidden_services/lnd/hostname to be created by tor...
externalip=XXX.onion:9735 added to /data/lnd.conf
[lnd_unlock] Waiting 2 seconds for lnd...
2020-09-14 22:49:26.214 [INF] LTND: Version: 0.11.0-beta commit=basedon-v0.11.0-beta-fresh-btcpay, build=production, logging=default
2020-09-14 22:49:26.215 [INF] LTND: Active chain: Bitcoin (network=mainnet)
2020-09-14 22:49:26.215 [INF] LTND: Opening the main database, this might take a few minutes...
2020-09-14 22:49:26.215 [INF] LTND: Opening bbolt database, sync_freelist=false
**panic: freepages: failed to get all reachable pages (page 7298: multiple references)**

goroutine 37 [running]:
go.etcd.io/bbolt.(*DB).freepages.func2(0xc0000b00c0)
	/go/pkg/mod/go.etcd.io/bbolt@v1.3.5-0.20200615073812-232d8fc87f50/db.go:1003 +0xe5
created by go.etcd.io/bbolt.(*DB).freepages
	/go/pkg/mod/go.etcd.io/bbolt@v1.3.5-0.20200615073812-232d8fc87f50/db.go:1001 +0x1ce

```

I have backups of my lnd (seeds and channels) from what I can see it looks like the database is corrupted or something. 

How can it be repaired, restored?

**Comment by Eskyee** [comment]
Since updating btcpayserver/lnd:v0.11.0-beta via btcpayupdate.sh on Lunanode I have not had any problems with lightning 🌩 LND , if that helps.

**Comment by vanjaime** [comment]
That's what I did but it looks like my db is corrupted. Is there a way to rebuild/restore?

**Comment by vanjaime** [comment]
Issue can be closed.
I deleted the entire lnd volume and started fresh from scratch.
