### ISSUE TITLE
nbxplorer restart.......

### ISSUE THREAD

**Issue by wakiyamap** [btcpayserver/btcpayserver-docker#398]
Please let me know if I'm wrong to listen here.
I rebooted after the update.
Then nbxplorer keeps restarting with the following error in nbxplorer.
Is there any way to verify the details of what is going on?

```
info: Configuration:  Data Directory: /datadir
info: Configuration:  Configuration File: /datadir/Main/settings.config
info: Configuration:  Network: Mainnet
info: Configuration:  Supported chains: MONA
info: Configuration:  DBCache: 50 MB
info: Configuration:  Network: Mainnet
info: Configuration:  Supported chains: MONA
info: Configuration:  DBCache: 50 MB
info: Explorer:       Defragmenting transaction tables...
info: Explorer:       Defragmentation succeed, 0 bytes saved
info: Explorer:       Applying migration if needed, do not close NBXplorer...
info: Explorer:       Trimming the event table if needed...
warn: Explorer:       MONA: Careful, you are probably running low on storage space, so we attempt defragmentation directly on the table, please do not close NBXplorer during the defragmentation.
Unhandled exception. System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at DBTrie.Extensions.BigEndianToLongDynamic(ReadOnlySpan`1 span)
   at DBTrie.TrieModel.LTrieNode..ctor(LTrie trie, Int32 minKeyLength, Int64 pointer, ReadOnlyMemory`1 memory)
   at DBTrie.TrieModel.LTrie.FetchNode(Int64 pointer, Int32 minKeyLength)
   at DBTrie.TrieModel.LTrie.ReadNode(Int64 pointer, Int32 minKeyLength, Boolean useCache)
   at DBTrie.TrieModel.LTrie.Defragment(CancellationToken cancellationToken)
   at DBTrie.Table.UnsafeDefragment(CancellationToken cancellationToken)
   at DBTrie.Table.UnsafeDefragment(CancellationToken cancellationToken)
   at DBTrie.Table.UnsafeDefragment(CancellationToken cancellationToken)
   at NBXplorer.Repository.Defragment(Transaction tx, Table table, CancellationToken cancellationToken) in /source/NBXplorer/Repository.cs:line 1322
   at NBXplorer.Repository.TrimmingEvents(Int32 maxEvents, CancellationToken cancellationToken) in /source/NBXplorer/Repository.cs:line 1308
   at NBXplorer.RepositoryProvider.StartAsync(CancellationToken cancellationToken) in /source/NBXplorer/Repository.cs:line 139
   at Microsoft.AspNetCore.Hosting.HostedServiceExecutor.ExecuteAsync(Func`2 callback, Boolean throwOnFirstFailure)
   at Microsoft.AspNetCore.Hosting.WebHost.StartAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String startupMessage)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String startupMessage)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host)
   at NBXplorer.Program.Main(String[] args) in /source/NBXplorer/Program.cs:line 60
```

```
# df -h
Filesystem      Size  Used Avail Use% Mounted on
udev            7.9G     0  7.9G   0% /dev
tmpfs           1.6G   25M  1.6G   2% /run
/dev/vda1        46G  7.6G   36G  18% /
```

```
2020-11-16 20:37:21.000 +00:00 [INF] MONA: Explorer url is http://nbxplorer:32838/
2020-11-16 20:37:21.096 +00:00 [INF] MONA: Cookie file is /root/.nbxplorer/Main/.cookie
2020-11-16 20:37:21.401 +00:00 [INF] Internal Socks HTTP Proxy listening at http://127.0.0.1:34197/
2020-11-16 20:37:21.465 +00:00 [INF] Starting listening NBXplorer (MONA)
2020-11-16 20:37:21.513 +00:00 [ERR] MONA: NBXplorer error `Connection refused`
2020-11-16 20:37:21.516 +00:00 [INF] Start watching invoices
2020-11-16 20:37:21.573 +00:00 [INF] Starting payment request expiration watcher
2020-11-16 20:37:21.825 +00:00 [INF] 2 pending payment requests being checked since last run
2020-11-16 20:38:21.523 +00:00 [ERR] MONA: NBXplorer error `Name or service not known`
2020-11-16 20:39:21.533 +00:00 [ERR] MONA: NBXplorer error `Name or service not known`
2020-11-16 20:40:21.543 +00:00 [ERR] MONA: NBXplorer error `Name or service not known`
2020-11-16 20:41:21.551 +00:00 [ERR] MONA: NBXplorer error `Name or service not known`
2020-11-16 20:42:21.569 +00:00 [ERR] MONA: NBXplorer error `Name or service not known`
2020-11-16 20:43:24.666 +00:00 [ERR] MONA: NBXplorer error `Connection refused`
2020-11-16 20:44:24.672 +00:00 [ERR] MONA: NBXplorer error `Name or service not known`
2020-11-16 20:45:24.681 +00:00 [ERR] MONA: NBXplorer error `Name or service not known`
2020-11-16 20:46:24.682 +00:00 [ERR] MONA: NBXplorer error `Name or service not known`
2020-11-16 20:47:24.699 +00:00 [ERR] MONA: NBXplorer error `Name or service not known`
```

**Comment by wakiyamap** [comment]
I fix it......
```
docker volume rm generated_nbxplorer_datadir
./btcpay_up.sh
```

Error has disappeared. Thanks.
