### ISSUE TITLE
Failed to deploy unexpected error

### ISSUE THREAD

**Issue by uhlhosting** [btcpayserver/btcpayserver-docker#441]
Greetings:

I have started a deployment process on a KVM machine inside a Promox, clean deployed machine, 1 external ip 4 GB ram, 4 CPU Cores. 400+ GB Storage.

- I am tackling with all possible combinations of fragments, up to this point, the error is not very helpfull, at least I do not know what is causing it yet.

Any help is appreciated.

```
. ./btcpay-setup.sh -i

-------SETUP-----------
Parameters passed:
BTCPAY_PROTOCOL:https
BTCPAY_HOST:btc.uhl.site
BTCPAY_ADDITIONAL_HOSTS:
REVERSEPROXY_HTTP_PORT:80
REVERSEPROXY_HTTPS_PORT:443
REVERSEPROXY_DEFAULT_HOST:none
LIBREPATRON_HOST:om.uhl.site
ZAMMAD_HOST:handson.uhl.site
WOOCOMMERCE_HOST:
BTCTRANSMUTER_HOST:store.uhl.site
BTCPAY_ENABLE_SSH:true
BTCPAY_HOST_SSHKEYFILE:
LETSENCRYPT_EMAIL:cosmin@uhl-services.ch
NBITCOIN_NETWORK:mainnet
LIGHTNING_ALIAS:UHL
BTCPAYGEN_CRYPTO1:btc
BTCPAYGEN_CRYPTO2:
BTCPAYGEN_CRYPTO3:
BTCPAYGEN_CRYPTO4:
BTCPAYGEN_CRYPTO5:
BTCPAYGEN_CRYPTO6:
BTCPAYGEN_CRYPTO7:
BTCPAYGEN_CRYPTO8:
BTCPAYGEN_CRYPTO9:
BTCPAYGEN_REVERSEPROXY:nginx
BTCPAYGEN_LIGHTNING:clightning
BTCPAYGEN_ADDITIONAL_FRAGMENTS:;opt-add-electrumx;opt-more-memory;opt-add-librepatron;op-add-zammad;opt-add-btctransmuter;opt-add-zammad;opt-add-librepatron;opt-add-configurator;opt-add-thunderhub;opt-monero-expose;opt-txindex;opt-add-btcqbo;opt-lnd-autopilot;opt-lnd-keysend;opt-add-configurator;opt-add-thunderhub;opt-monero-expose;opt-txindex;opt-add-btcqbo;opt-lnd-autopilot;opt-lnd-keysend;opt-add-electrumx;opt-more-memory;opt-add-librepatron;op-add-zammad;opt-add-btctransmuter;opt-add-zammad;opt-add-librepatron;opt-add-configurator;opt-add-thunderhub;opt-monero-expose;opt-txindex;opt-add-btcqbo;opt-lnd-autopilot;opt-lnd-keysend
BTCPAYGEN_EXCLUDE_FRAGMENTS:op-add-zammad
BTCPAY_IMAGE:
ACME_CA_URI:production
TOR_RELAY_NICKNAME: 
TOR_RELAY_EMAIL: 
PIHOLE_SERVERIP: 92.222.242.241
----------------------
Additional exported variables:
BTCPAY_DOCKER_COMPOSE=/home/ubuntu/BTCPayServer/btcpayserver-docker/Generated/docker-compose.generated.yml
BTCPAY_BASE_DIRECTORY=/home/ubuntu/BTCPayServer
BTCPAY_ENV_FILE=/home/ubuntu/BTCPayServer/.env
BTCPAYGEN_OLD_PREGEN=false
BTCPAY_SSHKEYFILE=/datadir/host_id_rsa
BTCPAY_SSHAUTHORIZEDKEYS=/datadir/host_authorized_keys
BTCPAY_HOST_SSHAUTHORIZEDKEYS:/root/.ssh/authorized_keys
BTCPAY_SSHTRUSTEDFINGERPRINTS:
BTCPAY_CRYPTOS:btc
BTCPAY_ANNOUNCEABLE_HOST:btc.uhl.site
----------------------

BTCPay Server environment variables successfully saved in /etc/profile.d/btcpay-env.sh

BTCPay Server docker-compose parameters saved in /home/ubuntu/BTCPayServer/.env

Using default tag: latest
latest: Pulling from btcpayserver/docker-compose-generator
Digest: sha256:ed69f844a6f640cd95d4816af6f054651e7ddbe069a72be0a299c4e1c69c6cfa
Status: Image is up to date for btcpayserver/docker-compose-generator:latest
docker.io/btcpayserver/docker-compose-generator:latest
Crypto: btc
Lightning: clightning
ReverseProxy: nginx
Generating /app/Generated/docker-compose.generated.yml
Selected fragments:
	nginx
	btcpayserver
	bitcoin
	bitcoin-clightning
	opt-add-electrumx
	opt-more-memory
	opt-add-librepatron
	opt-add-btctransmuter
	opt-add-zammad
	opt-add-configurator
	opt-add-thunderhub
	opt-monero-expose
	opt-txindex
	opt-add-btcqbo
	opt-lnd-autopilot
	opt-lnd-keysend
	btcpayserver-nginx
	postgres
	nbxplorer
	bitcoin-lnd
	monero
	nginx-https
	opt-add-tor
	opt-add-zmq
Unhandled exception. System.InvalidOperationException: Sequence contains more than one matching element
   at System.Linq.ThrowHelper.ThrowMoreThanOneMatchException()
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at DockerGenerator.DockerComposeDefinition.<>c.<Merge>b__23_2(IGrouping`2 group) in /source/DockerComposeDefinition.cs:line 216
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at DockerGenerator.DockerComposeDefinition.Merge(List`1 services) in /source/DockerComposeDefinition.cs:line 213
   at DockerGenerator.DockerComposeDefinition.Build() in /source/DockerComposeDefinition.cs:line 166
   at DockerGenerator.Program.Run(DockerComposition composition, String name, String output) in /source/Program.cs:line 102
   at DockerGenerator.Program.Main(String[] args) in /source/Program.cs:line 28
Failed to generate the docker-compose
root@btc:/home/ubuntu/BTCPayServer/btcpayserver-docker# 

```

**Comment by uhlhosting** [comment]
It was some syntax issue, managed to solve it.
