### ISSUE TITLE
The lnd works fine but the c-lightning not (invoices)

### ISSUE THREAD

**Issue by Perlover** [btcpayserver/btcpayserver-docker#50]
Hello!

I got errors (a generation an invoice from `app`) from c-lightning as:

    {"error":"No payment method available for this store\n10/9/18 4:06:39 PM: Creation of invoice starting\n10/9/18 4:06:39 PM: BTC_CZK: The rating rule is coinaverage(BTC_CZK)\n10/9/18 4:06:39 PM: BTC_CZK: The evaluated rating rule is 148972.603090763\n10/9/18 4:06:39 PM: BTC_USD: The rating rule is coinaverage(BTC_USD)\n10/9/18 4:06:39 PM: BTC_USD: The evaluated rating rule is 6613.95322581253\n10/9/18 4:06:40 PM: BTC: The amount of the invoice is too low to be paid on chain\n10/9/18 4:06:44 PM: BTC: Payment method unavailable (Impossible to create lightning invoice (Resource temporarily unavailable))\n"}

When i try to create an invoice in the admin area throough web - i got same error but by red text in web

Before this:

I set up BTCPay (MS Azure - Docker container) with `lnd` - it works fine.
Then i changed config to c-lightning by:

    btcpay-down.sh
    export BTCPAYGEN_LIGHTNING=clightning
    . btcpay-setup.sh -i

`docker ps` shows to me the container 'btcpayserver_clightning_bitcoin'
There is logs as:

    Waiting for the node to start and sync
    BTC: Is offline
    -----trying again in 1 seconds-----
    BTC: Is offline
    -----trying again in 2 seconds-----
    BTC: Is offline
    -----trying again in 4 seconds-----
    BTC: Is offline
    -----trying again in 8 seconds-----
    BTC: Is offline
    -----trying again in 16 seconds-----
    BTC: Is fully synched
    Node synched
    Replaced network mainnet by bitcoin in /root/.lightning/config
    2018-10-09T16:05:29.076Z lightningd(35): Server started with public key 02c163829275ee68d33290f393459d57a1559af09307208bf0f3448d08e37e720c, alias  (color #02c163) and lightningd 3c8001d-modded
    2018-10-09T16:07:34.842Z lightningd(35): lightning_channeld-02908b1a203349f963d52a32cc12a19d06ee920380ed14ae01d1cfbc3f16886678 chan #3: Peer connection lost
    2018-10-09T16:07:34.842Z lightningd(35): 02908b1a203349f963d52a32cc12a19d06ee920380ed14ae01d1cfbc3f16886678 chan #3: Peer transient failure in CHANNELD_NORMAL: lightning_channeld: Owning subdaemon lightning_channeld died (62208)

Then i update BTCPay to last commit

Then i change `BTCPay` again to `lnd` - again it works fine. Then i changed to c-lightning - again same error (**Resource temporarily unavailable**). Through `cli` interface i can create invoice under c-lightning...

**Comment by Perlover** [comment]
I saw now a logs of BTCPay (`docker logs ...`)

Now i see many errors but when i had same error i didn't see same:

    info: Events:         BTC: New block
    fail: PayServer:      BTC (Lightning): Can't connect to the lightning server
    System.Net.Http.HttpRequestException: Resource temporarily unavailable ---> System.Net.Sockets.SocketException: Resource temporarily unavailable
       at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
       --- End of inner exception stack trace ---
       at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
       at System.Threading.Tasks.ValueTask`1.get_Result()
       at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
       at System.Threading.Tasks.ValueTask`1.get_Result()
       at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
       at System.Threading.Tasks.ValueTask`1.get_Result()
       at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
       at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
       at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
       at BTCPayServer.Lightning.LND.LndSwaggerClient.LookupInvoiceAsync(String r_hash_str, Byte[] r_hash, CancellationToken cancellationToken)
       at BTCPayServer.Lightning.LND.LndClient.BTCPayServer.Lightning.ILightningClient.GetInvoice(String invoiceId, CancellationToken cancellation)
       at BTCPayServer.Payments.Lightning.LightningListener.EnsureListening(String invoiceId, Boolean poll) in /source/Payments/Lightning/LightningListener.cs:line 105
    info: Events:         BTC: New block
    fail: PayServer:      BTC (Lightning): Can't connect to the lightning server
    System.Net.Http.HttpRequestException: Resource temporarily unavailable ---> System.Net.Sockets.SocketException: Resource temporarily unavailable
       at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
       --- End of inner exception stack trace ---
       at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
       at System.Threading.Tasks.ValueTask`1.get_Result()
       at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
       at System.Threading.Tasks.ValueTask`1.get_Result()
       at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
       at System.Threading.Tasks.ValueTask`1.get_Result()
       at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
       at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
       at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
       at BTCPayServer.Lightning.LND.LndSwaggerClient.LookupInvoiceAsync(String r_hash_str, Byte[] r_hash, CancellationToken cancellationToken)
       at BTCPayServer.Lightning.LND.LndClient.BTCPayServer.Lightning.ILightningClient.GetInvoice(String invoiceId, CancellationToken cancellation)
       at BTCPayServer.Payments.Lightning.LightningListener.EnsureListening(String invoiceId, Boolean poll) in /source/Payments/Lightning/LightningListener.cs:line 105
    fail: PayServer:      BTC (Lightning): Can't connect to the lightning server
    System.Net.Http.HttpRequestException: Resource temporarily unavailable ---> System.Net.Sockets.SocketException: Resource temporarily unavailable
       at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
       --- End of inner exception stack trace ---
       at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
       at System.Threading.Tasks.ValueTask`1.get_Result()
       at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
       at System.Threading.Tasks.ValueTask`1.get_Result()
       at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
       at System.Threading.Tasks.ValueTask`1.get_Result()
       at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
       at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
       at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
       at BTCPayServer.Lightning.LND.LndSwaggerClient.LookupInvoiceAsync(String r_hash_str, Byte[] r_hash, CancellationToken cancellationToken)
       at BTCPayServer.Lightning.LND.LndClient.BTCPayServer.Lightning.ILightningClient.GetInvoice(String invoiceId, CancellationToken cancellation)
       at BTCPayServer.Payments.Lightning.LightningListener.EnsureListening(String invoiceId, Boolean poll) in /source/Payments/Lightning/LightningListener.cs:line 105
    fail: PayServer:      BTC (Lightning): Can't connect to the lightning server
    System.Net.Http.HttpRequestException: Resource temporarily unavailable ---> System.Net.Sockets.SocketException: Resource temporarily unavailable
       at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
       --- End of inner exception stack trace ---
       at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
       at System.Threading.Tasks.ValueTask`1.get_Result()
       at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
       at System.Threading.Tasks.ValueTask`1.get_Result()
       at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
       at System.Threading.Tasks.ValueTask`1.get_Result()
       at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
       at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
       at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
       at BTCPayServer.Lightning.LND.LndSwaggerClient.LookupInvoiceAsync(String r_hash_str, Byte[] r_hash, CancellationToken cancellationToken)
       at BTCPayServer.Lightning.LND.LndClient.BTCPayServer.Lightning.ILightningClient.GetInvoice(String invoiceId, CancellationToken cancellation)
       at BTCPayServer.Payments.Lightning.LightningListener.EnsureListening(String invoiceId, Boolean poll) in /source/Payments/Lightning/LightningListener.cs:line 105

**Comment by NicolasDorier** [comment]
Given the logs, you are using LND at the store level. Go to your store settings, and reconfigure the lightning connection string to use clightning. (Clicking in the `Click Here` button in the screen where to save the connection string)

**Comment by Perlover** [comment]
Thanks!
It works! I close ticket
P.S. May be about this to write in doc?

**Comment by NicolasDorier** [comment]
Feel free to make a PR to the [docs](https://github.com/btcpayserver/btcpayserver-doc). I also notified the Chief Docs Officer bitcoinshirt.
