### ISSUE TITLE
Update error

### ISSUE THREAD

**Issue by theDavidCoen** [btcpayserver/btcpayserver-docker#536]
I'm trying to update from version 1.1.2.0 to 1.2.4 but I cannot.
I tried with Server settings -> Mantainance -> Update 
and with SSH 
```
$ sudo su -
$ cd btcpayserver-docker
$ btcpay-update.sh
```

without success.
I also tried with
```
$ sudo su -
$ cd /root/btcpayserver-docker/
$ ./btcpay-down.sh
$ ./btcpay-update.sh
$ ./btcpay-up.sh
```
but I get this:
```
Already up-to-date.
Using default tag: latest
latest: Pulling from btcpayserver/docker-compose-generator
Digest: sha256:603ab55cd906cff7176acf800fbe8b6e900a5c12af94e2948ea9bbaa7264b58a
Status: Image is up to date for btcpayserver/docker-compose-generator:latest
docker.io/btcpayserver/docker-compose-generator:latest
Crypto: btc
Lightning: lnd
ReverseProxy: nginx
Generating /app/Generated/docker-compose.generated.yml
Unhandled exception. YamlDotNet.Core.SemanticErrorException: (Line: 1, Col: 1, Idx: 0) - (Line: 1, Col: 2, Idx: 1): While parsing a block mapping, did not find expected key.
   at YamlDotNet.Core.Parser.ParseBlockMappingKey(Boolean isFirst)
   at YamlDotNet.Core.Parser.StateMachine()
   at YamlDotNet.Core.Parser.MoveNext()
   at YamlDotNet.Core.ParserExtensions.Allow[T](IParser parser)
   at YamlDotNet.Core.ParserExtensions.Expect[T](IParser parser)
   at YamlDotNet.RepresentationModel.YamlMappingNode.Load(IParser parser, DocumentLoadingState state)
   at YamlDotNet.RepresentationModel.YamlMappingNode..ctor(IParser parser, DocumentLoadingState state)
   at YamlDotNet.RepresentationModel.YamlNode.ParseNode(IParser parser, DocumentLoadingState state)
   at YamlDotNet.RepresentationModel.YamlDocument..ctor(IParser parser)
   at YamlDotNet.RepresentationModel.YamlStream.Load(IParser parser)
   at YamlDotNet.RepresentationModel.YamlStream.Load(TextReader input)
   at DockerGenerator.DockerComposeDefinition.ParseDocument(FragmentName fragment) in /source/DockerComposeDefinition.cs:line 284
   at DockerGenerator.DockerComposeDefinition.<>c__DisplayClass20_0.<Build>b__9(FragmentName f) in /source/DockerComposeDefinition.cs:line 70
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at DockerGenerator.DockerComposeDefinition.Build() in /source/DockerComposeDefinition.cs:line 70
   at DockerGenerator.Program.Run(DockerComposition composition, String name, String output) in /source/Program.cs:line 102
   at DockerGenerator.Program.Main(String[] args) in /source/Program.cs:line 28
Failed to generate the docker-compose
```
and the dashboard shows 1.1.2.0.

Any idea?

**Comment by theDavidCoen** [comment]
Guys I solved it!
I added a custom fragment in the past. Now I removed it and this fixed the issue!
