### ISSUE TITLE
generated_clightning_bitcoin_charge_1 container keeps restarting with a "Cannot find module" error

### ISSUE THREAD

**Issue by ksdhans** [btcpayserver/btcpayserver-docker#591]
The generated_clightning_bitcoin_charge_1 on my system (Raspberry Pi 4) keeps restarting with the following in the log:
Error: Knex: run
$ npm install sqlite3 --save
Cannot find module '/opt/charged/node_modules/sqlite3/lib/binding/napi-v3-linux-arm64/node_sqlite3.node'
Require stack:
- /opt/charged/node_modules/sqlite3/lib/sqlite3-binding.js
- /opt/charged/node_modules/sqlite3/lib/sqlite3.js
- /opt/charged/node_modules/knex/lib/dialects/sqlite3/index.js
- /opt/charged/node_modules/knex/lib/config-resolver.js
- /opt/charged/node_modules/knex/lib/knex.js
- /opt/charged/node_modules/knex/lib/index.js
- /opt/charged/node_modules/knex/knex.js
- /opt/charged/dist/app.js
- /opt/charged/bin/charged
    at Client_SQLite3.initializeDriver (/opt/charged/node_modules/knex/lib/client.js:235:13)
    at Client_SQLite3.Client (/opt/charged/node_modules/knex/lib/client.js:69:10)
    at new Client_SQLite3 (/opt/charged/node_modules/knex/lib/dialects/sqlite3/index.js:17:10)
    at Knex (/opt/charged/node_modules/knex/lib/knex.js:14:28)
    at _callee2$ (/opt/charged/dist/app.js:24:31)
    at tryCatch (/opt/charged/node_modules/regenerator-runtime/runtime.js:63:40)
    at Generator.invoke [as _invoke] (/opt/charged/node_modules/regenerator-runtime/runtime.js:293:22)
    at Generator.next (/opt/charged/node_modules/regenerator-runtime/runtime.js:118:21)
    at asyncGeneratorStep (/opt/charged/dist/app.js:11:103)
    at _next (/opt/charged/dist/app.js:13:194)

It looks like the problem may be caused by the Debian image used in the container. See here:
https://github.com/docker-library/ghost/issues/157#issuecomment-429403378

**Comment by ksdhans** [comment]
This doesn't happen any more.
