### ISSUE TITLE
out of memory for querying API

### ISSUE THREAD

**Issue by joltcan** [btcpayserver/btcpayserver-docker#600]
We had a bunch of payments due to a product launch and when we use the API to query for open payments we are getting memory exceptions in generated_btcpayserver_1, generated_nbxplorer_1:

```
System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
fatal error: out of memory allocating heap arena map

warn: PayServer:      Unhandled exception in TransactionLabelMarkerHostedService
System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at Microsoft.EntityFrameworkCore.Diagnostics.Internal.RelationalCommandDiagnosticsLogger.CommandErrorAsync(IRelationalConnection connection, DbCommand command, DbContext context, DbCommandMethod executeMethod, Guid commandId, Guid connectionId, Exception exception, DateT
imeOffset startTime, TimeSpan duration, CommandSource commandSource, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(AsyncEnumerator enumerator, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.<>c__DisplayClass33_0`2.<<ExecuteAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementationAsync[TState,TResult](Func`4 operation, Func`4 verifySucceeded, TState state, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementationAsync[TState,TResult](Func`4 operation, Func`4 verifySucceeded, TState state, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at BTCPayServer.Services.WalletRepository.GetWalletInfo(WalletId walletId) in /source/BTCPayServer/Services/WalletRepository.cs:line 59
   at BTCPayServer.HostedServices.TransactionLabelMarkerHostedService.ProcessEvent(Object evt, CancellationToken cancellationToken) in /source/BTCPayServer/HostedServices/TransactionLabelMarkerHostedService.cs:line 75
   at BTCPayServer.HostedServices.EventHostedServiceBase.ProcessEvents(CancellationToken cancellationToken) in /source/BTCPayServer/HostedServices/EventHostedServiceBase.cs:line 38
```

And the containers are restarted. Is it possible to raise the memory for this not to happen? Is it nbxexplorer that is the first culprit?

**Comment by pavlenex** [comment]
@joltcan is this still relevant? Still facing a problem?

**Comment by joltcan** [comment]
Hey!

Since it crashed we started to not do api queries that way and started to investigate the blockchain ourselfs with our own bitcoind, so yes, I would assume it's still an issue. Let me know if I should test something.
