### ISSUE TITLE
lighting charge restarting

### ISSUE THREAD

**Issue by lanceray-grv** [btcpayserver/btcpayserver-docker#637]
lighting-charge 4.23-1standalone service keeps restarting after completing the 1.51 BTCPay update.  All other containers running fine.

CONTAINER ID   IMAGE                                                   COMMAND                  CREATED          STATUS                        PORTS                                                                      NAMES
967e98682a36   btcpayserver/letsencrypt-nginx-proxy-companion:1.12.2   "/bin/bash /app/entr…"   58 minutes ago   Up 31 minutes                                                                                            letsencrypt-nginx-proxy-companion
3a32bb2f5c53   btcpayserver/docker-gen:0.7.8                           "/usr/local/bin/dock…"   58 minutes ago   Up 31 minutes                                                                                            nginx-gen
ab02a1e83495   btcpayserver/btcpayserver:1.5.1                         "/app/docker-entrypo…"   58 minutes ago   Up 31 minutes                 49392/tcp                                                                  generated_btcpayserver_1
475f2a664d2b   shesek/spark-wallet:0.2.9-standalone                    "tini -g -- scripts/…"   58 minutes ago   Up 31 minutes                 9737/tcp                                                                   generated_clightning_bitcoin_spark_1
**06ff214c4e54   shesek/lightning-charge:0.4.23-1-standalone             "tini -g -- bin/dock…"   58 minutes ago   Restarting (1) 1 second** ago                                                                              generated_clightning_bitcoin_charge_1
61cdef37bf3e   saubyk/c-lightning-rest:0.7.0                           "/sbin/tini -g -- ./…"   58 minutes ago   Up 30 minutes                 3001/tcp, 4001/tcp                                                         generated_clightning_bitcoin_rest_1
7c39889cbb22   btcpayserver/lightning:v0.10.2                          "/usr/bin/tini -g --…"   58 minutes ago   Up 31 minutes                 0.0.0.0:9735->9735/tcp, :::9735->9735/tcp, 9835/tcp                        btcpayserver_clightning_bitcoin
fd817656e35e   nicolasdorier/nbxplorer:2.3.21                          "dotnet NBXplorer.dll"   58 minutes ago   Up 31 minutes                 32838/tcp                                                                  generated_nbxplorer_1
c517d9c14f1b   btcpayserver/docker-gen:0.7.8                           "/usr/local/bin/dock…"   58 minutes ago   Up 31 minutes                                                                                            tor-gen
aa2b02f2c7f4   btcpayserver/bitcoin:22.0-1                             "/entrypoint.sh bitc…"   58 minutes ago   Up 31 minutes                 8332-8333/tcp, 18332-18333/tcp, 18443-18444/tcp, 39388/tcp, 43782/tcp      btcpayserver_bitcoind
974800c6eb1c   btcpayserver/postgres:13.6                              "/migrate-docker-ent…"   58 minutes ago   Up 31 minutes                 5432/tcp                                                                   generated_postgres_1
31fbe1c33a74   nginx:1.16.0                                            "nginx -g 'daemon of…"   58 minutes ago   Up 31 minutes                 0.0.0.0:80->80/tcp, :::80->80/tcp, 0.0.0.0:443->443/tcp, :::443->443/tcp   nginx
e4f33212d277   shahanafarooqui/rtl:0.12.2                              "/sbin/tini -g -- no…"   58 minutes ago   Up 31 minutes                 3000/tcp                                                                   generated_bitcoin_rtl_1
19a20e8f7131   btcpayserver/tor:0.4.6.5                                "./entrypoint.sh tor"    58 minutes ago   Up 31 minutes                 9050-9051/tcp                                                              tor

**Comment by lanceray-grv** [comment]
btcpay:~# Error: Knex: run
$ npm install sqlite3 --save
Cannot find module '/opt/charged/node_modules/sqlite3/lib/binding/napi-v3-linux-arm64/node_sqlite3.node'
Require stack:
- /opt/charged/node_modules/sqlite3/lib/sqlite3-binding.js
- /opt/charged/node_modules/sqlite3/lib/sqlite3.js
- /opt/charged/node_modules/knex/lib/dialects/sqlite3/index.js
- /opt/charged/node_modules/knex/lib/config-resolver.js
- /opt/charged/node_modules/knex/lib/knex.js
- /opt/charged/node_modules/knex/lib/index.js
- /opt/charged/node_modules/knex/knex.js
- /opt/charged/dist/app.js
- /opt/charged/bin/charged
    at Client_SQLite3.initializeDriver (/opt/charged/node_modules/knex/lib/client.js:235:13)
    at Client_SQLite3.Client (/opt/charged/node_modules/knex/lib/client.js:69:10)
    at new Client_SQLite3 (/opt/charged/node_modules/knex/lib/dialects/sqlite3/index.js:17:10)
    at Knex (/opt/charged/node_modules/knex/lib/knex.js:14:28)
    at _callee2$ (/opt/charged/dist/app.js:24:31)
    at tryCatch (/opt/charged/node_modules/regenerator-runtime/runtime.js:63:40)
    at Generator.invoke [as _invoke] (/opt/charged/node_modules/regenerator-runtime/runtime.js:293:22)
    at Generator.next (/opt/charged/node_modules/regenerator-runtime/runtime.js:118:21)
    at asyncGeneratorStep (/opt/charged/dist/app.js:11:103)
    at _next (/opt/charged/dist/app.js:13:194)
