### ISSUE TITLE
Issue with Lets Encrypt Renewal

### ISSUE THREAD

**Issue by thisisforjimmy** [btcpayserver/btcpayserver-docker#749]
So right now I am getting an error that the certificate is expired. I have tried everything in your guides on how to force renew the certificate but its not working. I tried "docker restart letsencrypt-nginx-proxy-companion" and its not working. I changed the hostname to another hostname and then back and its still working. I restarted the BTCPAY Server. I confirmed it been updated. Not sure what they next step is. Is there a way to manually renew the certificate? Any help would be greatly appreciated.

**Comment by konstanzzz** [comment]
I have the same problem. Running `./force-renew` within the container produces the following error:

```
./force_renew 
/etc/nginx/certs/example.domain /app
Creating/renewal example.domain certificates... (example.domain)
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/simp_le.py", line 1565, in main
    return main_with_exceptions(cli_args)
  File "/usr/lib/python3.7/site-packages/simp_le.py", line 1549, in main_with_exceptions
    persist_new_data(args, existing_data)
  File "/usr/lib/python3.7/site-packages/simp_le.py", line 1408, in persist_new_data
    args, existing_data.account_key, existing_data.account_reg)
  File "/usr/lib/python3.7/site-packages/simp_le.py", line 1341, in registered_client
    directory = messages.Directory.from_json(net.get(args.server).json())
  File "/usr/lib/python3.7/site-packages/acme/client.py", line 1161, in get
    self._send_request('GET', url, **kwargs), content_type=content_type)
  File "/usr/lib/python3.7/site-packages/acme/client.py", line 1110, in _send_request
    response = self.session.request(method, url, *args, **kwargs)
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 519, in request
    prep = self.prepare_request(req)
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 462, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/usr/lib/python3.7/site-packages/requests/models.py", line 313, in prepare
    self.prepare_url(url, params)
  File "/usr/lib/python3.7/site-packages/requests/models.py", line 387, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL 'production': No schema supplied. Perhaps you meant http://production?
```

**Comment by Delitants** [comment]
Stuck with it too
17610b2e5cab:/app# ./force_renew 
[Thu Jan 11 08:15:33 UTC 2024] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 6
[Thu Jan 11 08:15:33 UTC 2024] Can not init api for: production.
[Thu Jan 11 08:15:33 UTC 2024] Create account key ok.
[Thu Jan 11 08:15:33 UTC 2024] Registering account: production
[Thu Jan 11 08:15:33 UTC 2024] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 6
[Thu Jan 11 08:15:33 UTC 2024] Could not get nonce, let's try again.
[Thu Jan 11 08:15:36 UTC 2024] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 6
[Thu Jan 11 08:15:36 UTC 2024] Could not get nonce, let's try again.
[Thu Jan 11 08:15:39 UTC 2024] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 6
[Thu Jan 11 08:15:39 UTC 2024] Could not get nonce, let's try again.
[Thu Jan 11 08:15:43 UTC 2024] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 6
[Thu Jan 11 08:15:43 UTC 2024] Could not get nonce, let's try again.
[Thu Jan 11 08:15:46 UTC 2024] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 6
[Thu Jan 11 08:15:46 UTC 2024] Could not get nonce, let's try again.
[Thu Jan 11 08:15:49 UTC 2024] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 6
[Thu Jan 11 08:15:49 UTC 2024] Could not get nonce, let's try again.
[Thu Jan 11 08:15:52 UTC 2024] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 6
[Thu Jan 11 08:15:52 UTC 2024] Could not get nonce, let's try again.
[Thu Jan 11 08:15:55 UTC 2024] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 6
[Thu Jan 11 08:15:55 UTC 2024] Could not get nonce, let's try again.
[Thu Jan 11 08:15:58 UTC 2024] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 6
[Thu Jan 11 08:15:58 UTC 2024] Could not get nonce, let's try again.
[Thu Jan 11 08:16:01 UTC 2024] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 6
[Thu Jan 11 08:16:01 UTC 2024] Could not get nonce, let's try again.
[Thu Jan 11 08:16:05 UTC 2024] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 6
[Thu Jan 11 08:16:05 UTC 2024] Could not get nonce, let's try again.
[Thu Jan 11 08:16:08 UTC 2024] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 6
[Thu Jan 11 08:16:08 UTC 2024] Could not get nonce, let's try again.
[Thu Jan 11 08:16:11 UTC 2024] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 6
[Thu Jan 11 08:16:11 UTC 2024] Could not get nonce, let's try again.
[Thu Jan 11 08:16:14 UTC 2024] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 6
[Thu Jan 11 08:16:14 UTC 2024] Could not get nonce, let's try again.
[Thu Jan 11 08:16:17 UTC 2024] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 6
[Thu Jan 11 08:16:17 UTC 2024] Could not get nonce, let's try again.
[Thu Jan 11 08:16:20 UTC 2024] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 6
[Thu Jan 11 08:16:20 UTC 2024] Could not get nonce, let's try again.

**Comment by konstanzzz** [comment]
> Stuck with it too 17610b2e5cab:/app# ./force_renew [Thu Jan 11 08:15:33 UTC 2024] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 6 [Thu Jan 11 08:15:33 UTC 2024] Can not init api for: production. [Thu Jan 11 08:15:33 UTC 2024] Create account key ok. [Thu Jan 11 08:15:33 UTC 2024] Registering account: production [Thu Jan 11 08:15:33 UTC 2024] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 6 [Thu Jan 11 08:15:33 UTC 2024] Could not get nonce, let's try again. [Thu Jan 11 08:15:36 UTC 2024] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 6 [Thu Jan 11 08:15:36 UTC 2024] Could not get nonce, let's try again. [Thu Jan 11 08:15:39 UTC 2024] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 6 [Thu Jan 11 08:15:39 UTC 2024] Could not get nonce, let's try again. [Thu Jan 11 08:15:43 UTC 2024] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 6 [Thu Jan 11 08:15:43 UTC 2024] Could not get nonce, let's try again. [Thu Jan 11 08:15:46 UTC 2024] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 6 [Thu Jan 11 08:15:46 UTC 2024] Could not get nonce, let's try again. [Thu Jan 11 08:15:49 UTC 2024] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 6 [Thu Jan 11 08:15:49 UTC 2024] Could not get nonce, let's try again. [Thu Jan 11 08:15:52 UTC 2024] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 6 [Thu Jan 11 08:15:52 UTC 2024] Could not get nonce, let's try again. [Thu Jan 11 08:15:55 UTC 2024] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 6 [Thu Jan 11 08:15:55 UTC 2024] Could not get nonce, let's try again. [Thu Jan 11 08:15:58 UTC 2024] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 6 [Thu Jan 11 08:15:58 UTC 2024] Could not get nonce, let's try again. [Thu Jan 11 08:16:01 UTC 2024] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 6 [Thu Jan 11 08:16:01 UTC 2024] Could not get nonce, let's try again. [Thu Jan 11 08:16:05 UTC 2024] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 6 [Thu Jan 11 08:16:05 UTC 2024] Could not get nonce, let's try again. [Thu Jan 11 08:16:08 UTC 2024] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 6 [Thu Jan 11 08:16:08 UTC 2024] Could not get nonce, let's try again. [Thu Jan 11 08:16:11 UTC 2024] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 6 [Thu Jan 11 08:16:11 UTC 2024] Could not get nonce, let's try again. [Thu Jan 11 08:16:14 UTC 2024] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 6 [Thu Jan 11 08:16:14 UTC 2024] Could not get nonce, let's try again. [Thu Jan 11 08:16:17 UTC 2024] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 6 [Thu Jan 11 08:16:17 UTC 2024] Could not get nonce, let's try again. [Thu Jan 11 08:16:20 UTC 2024] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 6 [Thu Jan 11 08:16:20 UTC 2024] Could not get nonce, let's try again.

I gave up on this issue a long time ago. Instead I opted to use a nginx as a reverse proxy so I can configure SSL cert generation/renewal myself.

https://docs.btcpayserver.org/FAQ/Deployment/#can-i-use-an-existing-nginx-server-as-a-reverse-proxy-with-ssl-termination

**Comment by Delitants** [comment]
> > Stuck with it too 17610b2e5cab:/app# ./force_renew [Thu Jan 11 08:15:33 UTC 2024] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 6 [Thu Jan 11 08:15:33 UTC 2024] Can not init api for: production. [Thu Jan 11 08:15:33 UTC 2024] Create account key ok. [Thu Jan 11 08:15:33 UTC 2024] Registering account: production [Thu Jan 11 08:15:33 UTC 2024] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 6 [Thu Jan 11 08:15:33 UTC 2024] Could not get nonce, let's try again. [Thu Jan 11 08:15:36 UTC 2024] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 6 [Thu Jan 11 08:15:36 UTC 2024] Could not get nonce, let's try again. [Thu Jan 11 08:15:39 UTC 2024] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 6 [Thu Jan 11 08:15:39 UTC 2024] Could not get nonce, let's try again. [Thu Jan 11 08:15:43 UTC 2024] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 6 [Thu Jan 11 08:15:43 UTC 2024] Could not get nonce, let's try again. [Thu Jan 11 08:15:46 UTC 2024] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 6 [Thu Jan 11 08:15:46 UTC 2024] Could not get nonce, let's try again. [Thu Jan 11 08:15:49 UTC 2024] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 6 [Thu Jan 11 08:15:49 UTC 2024] Could not get nonce, let's try again. [Thu Jan 11 08:15:52 UTC 2024] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 6 [Thu Jan 11 08:15:52 UTC 2024] Could not get nonce, let's try again. [Thu Jan 11 08:15:55 UTC 2024] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 6 [Thu Jan 11 08:15:55 UTC 2024] Could not get nonce, let's try again. [Thu Jan 11 08:15:58 UTC 2024] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 6 [Thu Jan 11 08:15:58 UTC 2024] Could not get nonce, let's try again. [Thu Jan 11 08:16:01 UTC 2024] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 6 [Thu Jan 11 08:16:01 UTC 2024] Could not get nonce, let's try again. [Thu Jan 11 08:16:05 UTC 2024] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 6 [Thu Jan 11 08:16:05 UTC 2024] Could not get nonce, let's try again. [Thu Jan 11 08:16:08 UTC 2024] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 6 [Thu Jan 11 08:16:08 UTC 2024] Could not get nonce, let's try again. [Thu Jan 11 08:16:11 UTC 2024] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 6 [Thu Jan 11 08:16:11 UTC 2024] Could not get nonce, let's try again. [Thu Jan 11 08:16:14 UTC 2024] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 6 [Thu Jan 11 08:16:14 UTC 2024] Could not get nonce, let's try again. [Thu Jan 11 08:16:17 UTC 2024] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 6 [Thu Jan 11 08:16:17 UTC 2024] Could not get nonce, let's try again. [Thu Jan 11 08:16:20 UTC 2024] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 6 [Thu Jan 11 08:16:20 UTC 2024] Could not get nonce, let's try again.
> 
> I gave up on this issue a long time ago. Instead I opted to use a nginx as a reverse proxy so I can configure SSL cert generation/renewal myself.
> 
> https://docs.btcpayserver.org/FAQ/Deployment/#can-i-use-an-existing-nginx-server-as-a-reverse-proxy-with-ssl-termination

I have gave up on this LE too, and set up a free CloudFlare tunnel to bypass it. Worked. Can access dashboard again. https://docs.btcpayserver.org/Docker/cloudflare-tunnel/
