### ISSUE TITLE
No Database Configured Error even tho it is.

### ISSUE THREAD

**Issue by FuckingToasters** [btcpayserver/btcpayserver-docker#851]
Hello, so here is my docker-compose.yml file:
```yml
version: "3"

services:
  bitcoind:
    container_name: bitcoind
    restart: always
    image: "btcpayserver/bitcoin:25.0"
    environment:
      BITCOIN_NETWORK: regtest
      BITCOIN_EXTRA_ARGS: |
        rpcbind=bitcoind:18443
    volumes:
      - bitcoind_data:/data
    networks:
      - webproxy

  nbxplorer:
    container_name: nbxplorer
    restart: always
    image: "nicolasdorier/nbxplorer:2.4.1"
    environment:
      NBXPLORER_NETWORK: ${NBITCOIN_NETWORK:-regtest} 
      NBXPLORER_CHAINS: btc
      NBXPLORER_SIGNALFILEDIR: /datadir
      NBXPLORER_BTCRPCURL: http://bitcoind:18443
      NBXPLORER_BTCNODEENDPOINT: bitcoind:18444
    volumes:
      - bitcoind_data:/root/.bitcoin
      - nbxplorer_data:/datadir
    networks:
      - webproxy

  btcpay:
    container_name: btcpay
    restart: always
    image: "btcpayserver/btcpayserver:1.11.7-afrobitcoin-rc7-altcoins"
    environment:
      BTCPAY_PSTGRES: User ID=postgres;Host=postgres;Port=5432;Database=btcpayserverregtest
      BTCPAY_NETWORK: regtest
      BTCPAY_ROOTPATH: /
      BTCPAY_CHAINS: btc
      BTCPAY_SOCKSENDPOINT: tor:9050
      BTCPAY_TORRCFILE: /usr/local/etc/tor/torrc-2
      BTCPAY_BTCEXPLORERURL: http://nbxplorer:32838
      HIDDENSERVICE_NAME: BTCPayServer
    volumes:
      - btcpay_data:/datadir
      - nbxplorer_data:/root/.nbxplorer
      - torrc_data:/usr/local/etc/tor/
      - torservice_data:/var/lib/tor/hidden_services
    networks:
      - webproxy
    depends_on:
      - nbxplorer
      - postgres
      - tor

  postgres:
    container_name: postgres
    restart: always
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - webproxy

  tor: 
    container_name: tor
    restart: always
    image: "btcpayserver/tor:0.4.8.7"
    environment:
      TOR_PASSWORD: btcpayserver
      TOR_ADDITIONAL_CONFIG: /usr/local/etc/tor/torrc-2
      TOR_EXTRA_ARGS: |
        CookieAuthentication 1
    volumes:
      - torrc_data:/usr/local/etc/tor
      - torservice_data:/var/lib/tor/hidden_services
    networks:
      - webproxy

  tor-gen:
    container_name: tor-gen
    restart: always
    image: "btcpayserver/docker-gen:0.7.8"
    entrypoint: /usr/local/bin/docker-gen -notify-sighup tor -watch -wait 5s:30s /etc/docker-gen/templates/torrc.tmpl /usr/local/etc/tor/torrc-2
    volumes:
        - "/var/run/docker.sock:/tmp/docker.sock:ro"
        - "./torrc.tmpl:/etc/docker-gen/templates/torrc.tmpl:ro"
        - "torrc_data:/usr/local/etc/tor"
    networks:
      - webproxy

volumes:
  bitcoind_data:
  nbxplorer_data:
  btcpay_data:
  postgres_data:
  torrc_data:
  torservice_data:

networks:
  webproxy:
    external: true
```
(as you can see, it include postgres configuration)

The Error Logs:
```
info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer.Plugins.NFC - 1.11.7
info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer.Plugins.Crowdfund - 1.11.7
info: Configuration:  Supported chains: BTC
Unhandled exception. System.InvalidOperationException: No database option was configured.
   at BTCPayServer.Hosting.BTCPayServerServices.<>c__DisplayClass1_0.<AddBTCPayServer>b__11(DatabaseOptions options, IOptions`1 datadirs) in /source/BTCPayServer/Hosting/BTCPayServerServices.cs:line 186
   at Microsoft.Extensions.Options.ConfigureNamedOptions`2.Configure(String name, TOptions options)
   at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
   at Microsoft.Extensions.Options.UnnamedOptionsManager`1.get_Value()
   at BTCPayServer.Abstractions.Contracts.BaseDbContextFactory`1.ConfigureBuilder(DbContextOptionsBuilder builder) in /source/BTCPayServer.Abstractions/Contracts/BaseDbContextFactory.cs:line 71
   at BTCPayServer.Hosting.BTCPayServerServices.<>c.<AddBTCPayServer>b__1_2(IServiceProvider provider, DbContextOptionsBuilder o) in /source/BTCPayServer/Hosting/BTCPayServerServices.cs:line 89
   at Microsoft.Extensions.DependencyInjection.EntityFrameworkServiceCollectionExtensions.CreateDbContextOptions[TContext](IServiceProvider applicationServiceProvider, Action`2 optionsAction)
   at Microsoft.Extensions.DependencyInjection.EntityFrameworkServiceCollectionExtensions.<>c__DisplayClass17_0`1.<AddCoreServices>b__0(IServiceProvider p)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitIEnumerable(IEnumerableCallSite enumerableCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass2_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetServices[T](IServiceProvider provider)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.StartWithTasksAsync(IWebHost webHost, CancellationToken cancellationToken)
   at BTCPayServer.Program.Main(String[] args) in /source/BTCPayServer/Program.cs:line 77
bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
info: Configuration:  Data Directory: /datadir
info: Configuration:  Configuration File: /datadir/RegTest/settings.config
info: BTCPayServer.Plugins.PluginManager: Loading plugins from /root/.btcpayserver/Plugins
info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer - 1.11.7
info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer.Plugins.Shopify - 1.11.7
info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer.Plugins.PointOfSale - 1.11.7
info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer.Plugins.PayButton - 1.11.7
info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer.Plugins.NFC - 1.11.7
info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer.Plugins.Crowdfund - 1.11.7
info: Configuration:  Supported chains: BTC
Unhandled exception. System.InvalidOperationException: No database option was configured.
   at BTCPayServer.Hosting.BTCPayServerServices.<>c__DisplayClass1_0.<AddBTCPayServer>b__11(DatabaseOptions options, IOptions`1 datadirs) in /source/BTCPayServer/Hosting/BTCPayServerServices.cs:line 186
   at Microsoft.Extensions.Options.ConfigureNamedOptions`2.Configure(String name, TOptions options)
   at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
   at Microsoft.Extensions.Options.UnnamedOptionsManager`1.get_Value()
   at BTCPayServer.Abstractions.Contracts.BaseDbContextFactory`1.ConfigureBuilder(DbContextOptionsBuilder builder) in /source/BTCPayServer.Abstractions/Contracts/BaseDbContextFactory.cs:line 71
   at BTCPayServer.Hosting.BTCPayServerServices.<>c.<AddBTCPayServer>b__1_2(IServiceProvider provider, DbContextOptionsBuilder o) in /source/BTCPayServer/Hosting/BTCPayServerServices.cs:line 89
   at Microsoft.Extensions.DependencyInjection.EntityFrameworkServiceCollectionExtensions.CreateDbContextOptions[TContext](IServiceProvider applicationServiceProvider, Action`2 optionsAction)
   at Microsoft.Extensions.DependencyInjection.EntityFrameworkServiceCollectionExtensions.<>c__DisplayClass17_0`1.<AddCoreServices>b__0(IServiceProvider p)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitIEnumerable(IEnumerableCallSite enumerableCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass2_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetServices[T](IServiceProvider provider)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.StartWithTasksAsync(IWebHost webHost, CancellationToken cancellationToken)
   at BTCPayServer.Program.Main(String[] args) in /source/BTCPayServer/Program.cs:line 77
   ```

**Comment by dennisreimann** [comment]
There's a typo in `BTCPAY_PSTGRES` -> `BTCPAY_POSTGRES`.

**Comment by dennisreimann** [comment]
That's `49392`, see the exposed port on the reference I linked to. Is there a particular reason why you aren't using the standard Docker deployment?

**Comment by FuckingToasters** [comment]
> That's `49392`, see the exposed port on the reference I linked to. Is there a particular reason why you aren't using the standard Docker deployment?

That's because i not found the docker compose file inside this github repo so i used one from an youtube video.

I now added the one you mentioned with some modifications like network etc however, this now causes following error:
```
failed to pull images of the stack: time="2023-11-27T16:22:46Z" level=warning msg="The \"BTCPAY_SSHAUTHORIZEDKEYS\" variable is not set. Defaulting to a blank string." time="2023-11-27T16:22:46Z" level=warning msg="The \"BTCPAY_SSHKEYFILE\" variable is not set. Defaulting to a blank string." time="2023-11-27T16:22:46Z" level=warning msg="The \"BTCPAY_SSHAUTHORIZEDKEYS\" variable is not set. Defaulting to a blank string." time="2023-11-27T16:22:46Z" level=warning msg="The \"BTCPAY_SSHTRUSTEDFINGERPRINTS\" variable is not set. Defaulting to a blank string." 1 error(s) decoding: * error decoding 'volumes[2]': invalid spec: $<BTCPAY_HOST_SSHAUTHORIZEDKEYS>?:: empty section between colons 
```
